/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateProcOr105pk0CpyfabinsCpyFabRequest implements Serializable {


    @JsonProperty("pPrgId")
    private String pprgId;

    @JsonProperty("pDestordnum")
    private String pdestordnum;

    @JsonProperty("pSrcOrdnum")
    private String psrcOrdnum;

    @JsonProperty("pSrcFabseq")
    private String psrcFabseq;

    @JsonProperty("pChkFablibMat")
    private String pchkFablibMat;

    @JsonProperty("pChkOrdfab")
    private String pchkOrdfab;

    @JsonProperty("pExpFaborienReq")
    private String pexpFaborienReq;

    @JsonProperty("pExpFaborien")
    private Integer pexpFaborien;

    @JsonProperty("pExpMarkertypReq")
    private String pexpMarkertypReq;

    @JsonProperty("pExpMarkertyp")
    private String pexpMarkertyp;

    @JsonProperty("pSrcintrefno")
    private String psrcintrefno;

    @JsonProperty("pSrcintrefnoVer")
    private Integer psrcintrefnoVer;

    @JsonProperty("pSrcshadeopt")
    private String psrcshadeopt;

    @JsonProperty("pExpFaborienCondmsg")
    private String pexpFaborienCondmsg;

    @JsonProperty("pExpMarkertypCondmsg")
    private String pexpMarkertypCondmsg;

    @JsonProperty("pFaceside")
    private String pfaceside;

    public String getPprgId() {
        return this.pprgId;
    }

    public void setPprgId(String pprgId) {
        this.pprgId = pprgId;
    }

    public String getPdestordnum() {
        return this.pdestordnum;
    }

    public void setPdestordnum(String pdestordnum) {
        this.pdestordnum = pdestordnum;
    }

    public String getPsrcOrdnum() {
        return this.psrcOrdnum;
    }

    public void setPsrcOrdnum(String psrcOrdnum) {
        this.psrcOrdnum = psrcOrdnum;
    }

    public String getPsrcFabseq() {
        return this.psrcFabseq;
    }

    public void setPsrcFabseq(String psrcFabseq) {
        this.psrcFabseq = psrcFabseq;
    }

    public String getPchkFablibMat() {
        return this.pchkFablibMat;
    }

    public void setPchkFablibMat(String pchkFablibMat) {
        this.pchkFablibMat = pchkFablibMat;
    }

    public String getPchkOrdfab() {
        return this.pchkOrdfab;
    }

    public void setPchkOrdfab(String pchkOrdfab) {
        this.pchkOrdfab = pchkOrdfab;
    }

    public String getPexpFaborienReq() {
        return this.pexpFaborienReq;
    }

    public void setPexpFaborienReq(String pexpFaborienReq) {
        this.pexpFaborienReq = pexpFaborienReq;
    }

    public Integer getPexpFaborien() {
        return this.pexpFaborien;
    }

    public void setPexpFaborien(Integer pexpFaborien) {
        this.pexpFaborien = pexpFaborien;
    }

    public String getPexpMarkertypReq() {
        return this.pexpMarkertypReq;
    }

    public void setPexpMarkertypReq(String pexpMarkertypReq) {
        this.pexpMarkertypReq = pexpMarkertypReq;
    }

    public String getPexpMarkertyp() {
        return this.pexpMarkertyp;
    }

    public void setPexpMarkertyp(String pexpMarkertyp) {
        this.pexpMarkertyp = pexpMarkertyp;
    }

    public String getPsrcintrefno() {
        return this.psrcintrefno;
    }

    public void setPsrcintrefno(String psrcintrefno) {
        this.psrcintrefno = psrcintrefno;
    }

    public Integer getPsrcintrefnoVer() {
        return this.psrcintrefnoVer;
    }

    public void setPsrcintrefnoVer(Integer psrcintrefnoVer) {
        this.psrcintrefnoVer = psrcintrefnoVer;
    }

    public String getPsrcshadeopt() {
        return this.psrcshadeopt;
    }

    public void setPsrcshadeopt(String psrcshadeopt) {
        this.psrcshadeopt = psrcshadeopt;
    }

    public String getPexpFaborienCondmsg() {
        return this.pexpFaborienCondmsg;
    }

    public void setPexpFaborienCondmsg(String pexpFaborienCondmsg) {
        this.pexpFaborienCondmsg = pexpFaborienCondmsg;
    }

    public String getPexpMarkertypCondmsg() {
        return this.pexpMarkertypCondmsg;
    }

    public void setPexpMarkertypCondmsg(String pexpMarkertypCondmsg) {
        this.pexpMarkertypCondmsg = pexpMarkertypCondmsg;
    }

    public String getPfaceside() {
        return this.pfaceside;
    }

    public void setPfaceside(String pfaceside) {
        this.pfaceside = pfaceside;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateProcOr105pk0CpyfabinsCpyFabRequest)) return false;
        final CreateProcOr105pk0CpyfabinsCpyFabRequest createProcOr105pk0cpyfabinsCpyFabRequest = (CreateProcOr105pk0CpyfabinsCpyFabRequest) o;
        return Objects.equals(getPprgId(), createProcOr105pk0cpyfabinsCpyFabRequest.getPprgId()) &&
                Objects.equals(getPdestordnum(), createProcOr105pk0cpyfabinsCpyFabRequest.getPdestordnum()) &&
                Objects.equals(getPsrcOrdnum(), createProcOr105pk0cpyfabinsCpyFabRequest.getPsrcOrdnum()) &&
                Objects.equals(getPsrcFabseq(), createProcOr105pk0cpyfabinsCpyFabRequest.getPsrcFabseq()) &&
                Objects.equals(getPchkFablibMat(), createProcOr105pk0cpyfabinsCpyFabRequest.getPchkFablibMat()) &&
                Objects.equals(getPchkOrdfab(), createProcOr105pk0cpyfabinsCpyFabRequest.getPchkOrdfab()) &&
                Objects.equals(getPexpFaborienReq(), createProcOr105pk0cpyfabinsCpyFabRequest.getPexpFaborienReq()) &&
                Objects.equals(getPexpFaborien(), createProcOr105pk0cpyfabinsCpyFabRequest.getPexpFaborien()) &&
                Objects.equals(getPexpMarkertypReq(), createProcOr105pk0cpyfabinsCpyFabRequest.getPexpMarkertypReq()) &&
                Objects.equals(getPexpMarkertyp(), createProcOr105pk0cpyfabinsCpyFabRequest.getPexpMarkertyp()) &&
                Objects.equals(getPsrcintrefno(), createProcOr105pk0cpyfabinsCpyFabRequest.getPsrcintrefno()) &&
                Objects.equals(getPsrcintrefnoVer(), createProcOr105pk0cpyfabinsCpyFabRequest.getPsrcintrefnoVer()) &&
                Objects.equals(getPsrcshadeopt(), createProcOr105pk0cpyfabinsCpyFabRequest.getPsrcshadeopt()) &&
                Objects.equals(getPexpFaborienCondmsg(), createProcOr105pk0cpyfabinsCpyFabRequest.getPexpFaborienCondmsg()) &&
                Objects.equals(getPexpMarkertypCondmsg(), createProcOr105pk0cpyfabinsCpyFabRequest.getPexpMarkertypCondmsg()) &&
                Objects.equals(getPfaceside(), createProcOr105pk0cpyfabinsCpyFabRequest.getPfaceside());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgId(),
                getPdestordnum(),
                getPsrcOrdnum(),
                getPsrcFabseq(),
                getPchkFablibMat(),
                getPchkOrdfab(),
                getPexpFaborienReq(),
                getPexpFaborien(),
                getPexpMarkertypReq(),
                getPexpMarkertyp(),
                getPsrcintrefno(),
                getPsrcintrefnoVer(),
                getPsrcshadeopt(),
                getPexpFaborienCondmsg(),
                getPexpMarkertypCondmsg(),
                getPfaceside());
    }
}