/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class CreateProcOr105pk0CpyfabinsCpyFabResponse implements Serializable {


    @ColumnAlias("pOutNewfabseq")
    private Integer poutNewfabseq;

    public Integer getPoutNewfabseq() {
        return this.poutNewfabseq;
    }

    public void setPoutNewfabseq(Integer poutNewfabseq) {
        this.poutNewfabseq = poutNewfabseq;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateProcOr105pk0CpyfabinsCpyFabResponse)) return false;
        final CreateProcOr105pk0CpyfabinsCpyFabResponse createProcOr105pk0cpyfabinsCpyFabResponse = (CreateProcOr105pk0CpyfabinsCpyFabResponse) o;
        return Objects.equals(getPoutNewfabseq(), createProcOr105pk0cpyfabinsCpyFabResponse.getPoutNewfabseq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutNewfabseq());
    }
}