/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or105wpk0qryOrt125ResponsePoutYrnlist implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("YRNSEQ")
    private Byte yrnseq;

    @ColumnAlias("YRNCNT")
    private String yrncnt;

    @ColumnAlias("YRNCPS")
    private String yrncps;

    @ColumnAlias("YRNCLR")
    private String yrnclr;

    @ColumnAlias("ORICLR")
    private String oriclr;

    @ColumnAlias("CLRREF")
    private String clrref;

    @ColumnAlias("WCLRREFSHADEDES")
    private String wclrrefshadedes;

    @ColumnAlias("YRNORI")
    private String yrnori;

    @ColumnAlias("YRNQLTY")
    private String yrnqlty;

    @ColumnAlias("YRNSUBQLTYA")
    private String yrnsubqltya;

    @ColumnAlias("YRNSUBQLTYB")
    private String yrnsubqltyb;

    @ColumnAlias("YRNFFCOD")
    private String yrnffcod;

    @ColumnAlias("WYRNFFDESC")
    private String wyrnffdesc;

    @ColumnAlias("NUMROWS")
    private Short numrows;

    @ColumnAlias("TOTROWS")
    private Short totrows;

    @ColumnAlias("YRNFRAC")
    private Float yrnfrac;

    @ColumnAlias("TIPPING")
    private String tipping;

    @ColumnAlias("YRNENDS")
    private Short yrnends;

    @ColumnAlias("PRECLRREF")
    private String preclrref;

    @ColumnAlias("INILABDIPNO")
    private String inilabdipno;

    @ColumnAlias("INILABREVNO")
    private Short inilabrevno;

    @ColumnAlias("INILABADDNO")
    private Short inilabaddno;

    @ColumnAlias("INILABAPPRVDATE")
    private LocalDateTime inilabapprvdate;

    @ColumnAlias("LABAPPRVDATE")
    private LocalDateTime labapprvdate;

    @ColumnAlias("LABAPPRVID")
    private String labapprvid;

    @ColumnAlias("RELATED_LABDIPNO")
    private String relatedLabdipno;

    @ColumnAlias("RELATED_LABDIPREM")
    private String relatedLabdiprem;

    @ColumnAlias("RELATED_LABDIP_LSTID")
    private String relatedLabdipLstid;

    @ColumnAlias("RELATED_LABDIP_LSTDATE")
    private LocalDateTime relatedLabdipLstdate;

    @ColumnAlias("BASE_YRNCLR")
    private String baseYrnclr;

    @ColumnAlias("BASE_CLRREF")
    private String baseClrref;

    @ColumnAlias("BASE_YRNCDES")
    private String baseYrncdes;

    @ColumnAlias("LABTOAPP")
    private String labtoapp;

    @ColumnAlias("WREQLABDIPSTS")
    private String wreqlabdipsts;

    @ColumnAlias("WLABDIPSTS")
    private String wlabdipsts;

    @ColumnAlias("WLABDIPNO")
    private String wlabdipno;

    @ColumnAlias("WREVNO")
    private String wrevno;

    @ColumnAlias("WADDNO")
    private String waddno;

    @ColumnAlias("WPRECLRREF")
    private String wpreclrref;

    @ColumnAlias("WYRNCDESLOV")
    private String wyrncdeslov;

    @ColumnAlias("WREQLABDIP")
    private String wreqlabdip;

    @ColumnAlias("WAPPRVLABDIP")
    private String wapprvlabdip;

    @ColumnAlias("YRNCNTEDITACS")
    private String yrncnteditacs;

    @ColumnAlias("YRNCPSEDITACS")
    private String yrncpseditacs;

    @ColumnAlias("YRNQLTYEDITACS")
    private String yrnqltyeditacs;

    @ColumnAlias("YRNSUBQLTYAEDITACS")
    private String yrnsubqltyaeditacs;

    @ColumnAlias("YRNSUBQLTYBEDITACS")
    private String yrnsubqltybeditacs;

    @ColumnAlias("YRNCLREDITACS")
    private String yrnclreditacs;

    @ColumnAlias("YRNFFCODEDITACS")
    private String yrnffcodeditacs;

    @ColumnAlias("BASEYRNCLREDITACS")
    private String baseyrnclreditacs;

    @ColumnAlias("YRNFRACEDITACS")
    private String yrnfraceditacs;

    @ColumnAlias("CLRREFEDITACS")
    private String clrrefeditacs;

    @ColumnAlias("ORICLREDITACS")
    private String oriclreditacs;

    @ColumnAlias("PRECLRREFEDITACS")
    private String preclrrefeditacs;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public Byte getYrnseq() {
        return this.yrnseq;
    }

    public void setYrnseq(Byte yrnseq) {
        this.yrnseq = yrnseq;
    }

    public String getYrncnt() {
        return this.yrncnt;
    }

    public void setYrncnt(String yrncnt) {
        this.yrncnt = yrncnt;
    }

    public String getYrncps() {
        return this.yrncps;
    }

    public void setYrncps(String yrncps) {
        this.yrncps = yrncps;
    }

    public String getYrnclr() {
        return this.yrnclr;
    }

    public void setYrnclr(String yrnclr) {
        this.yrnclr = yrnclr;
    }

    public String getOriclr() {
        return this.oriclr;
    }

    public void setOriclr(String oriclr) {
        this.oriclr = oriclr;
    }

    public String getClrref() {
        return this.clrref;
    }

    public void setClrref(String clrref) {
        this.clrref = clrref;
    }

    public String getWclrrefshadedes() {
        return this.wclrrefshadedes;
    }

    public void setWclrrefshadedes(String wclrrefshadedes) {
        this.wclrrefshadedes = wclrrefshadedes;
    }

    public String getYrnori() {
        return this.yrnori;
    }

    public void setYrnori(String yrnori) {
        this.yrnori = yrnori;
    }

    public String getYrnqlty() {
        return this.yrnqlty;
    }

    public void setYrnqlty(String yrnqlty) {
        this.yrnqlty = yrnqlty;
    }

    public String getYrnsubqltya() {
        return this.yrnsubqltya;
    }

    public void setYrnsubqltya(String yrnsubqltya) {
        this.yrnsubqltya = yrnsubqltya;
    }

    public String getYrnsubqltyb() {
        return this.yrnsubqltyb;
    }

    public void setYrnsubqltyb(String yrnsubqltyb) {
        this.yrnsubqltyb = yrnsubqltyb;
    }

    public String getYrnffcod() {
        return this.yrnffcod;
    }

    public void setYrnffcod(String yrnffcod) {
        this.yrnffcod = yrnffcod;
    }

    public String getWyrnffdesc() {
        return this.wyrnffdesc;
    }

    public void setWyrnffdesc(String wyrnffdesc) {
        this.wyrnffdesc = wyrnffdesc;
    }

    public Short getNumrows() {
        return this.numrows;
    }

    public void setNumrows(Short numrows) {
        this.numrows = numrows;
    }

    public Short getTotrows() {
        return this.totrows;
    }

    public void setTotrows(Short totrows) {
        this.totrows = totrows;
    }

    public Float getYrnfrac() {
        return this.yrnfrac;
    }

    public void setYrnfrac(Float yrnfrac) {
        this.yrnfrac = yrnfrac;
    }

    public String getTipping() {
        return this.tipping;
    }

    public void setTipping(String tipping) {
        this.tipping = tipping;
    }

    public Short getYrnends() {
        return this.yrnends;
    }

    public void setYrnends(Short yrnends) {
        this.yrnends = yrnends;
    }

    public String getPreclrref() {
        return this.preclrref;
    }

    public void setPreclrref(String preclrref) {
        this.preclrref = preclrref;
    }

    public String getInilabdipno() {
        return this.inilabdipno;
    }

    public void setInilabdipno(String inilabdipno) {
        this.inilabdipno = inilabdipno;
    }

    public Short getInilabrevno() {
        return this.inilabrevno;
    }

    public void setInilabrevno(Short inilabrevno) {
        this.inilabrevno = inilabrevno;
    }

    public Short getInilabaddno() {
        return this.inilabaddno;
    }

    public void setInilabaddno(Short inilabaddno) {
        this.inilabaddno = inilabaddno;
    }

    public LocalDateTime getInilabapprvdate() {
        return this.inilabapprvdate;
    }

    public void setInilabapprvdate(LocalDateTime inilabapprvdate) {
        this.inilabapprvdate = inilabapprvdate;
    }

    public LocalDateTime getLabapprvdate() {
        return this.labapprvdate;
    }

    public void setLabapprvdate(LocalDateTime labapprvdate) {
        this.labapprvdate = labapprvdate;
    }

    public String getLabapprvid() {
        return this.labapprvid;
    }

    public void setLabapprvid(String labapprvid) {
        this.labapprvid = labapprvid;
    }

    public String getRelatedLabdipno() {
        return this.relatedLabdipno;
    }

    public void setRelatedLabdipno(String relatedLabdipno) {
        this.relatedLabdipno = relatedLabdipno;
    }

    public String getRelatedLabdiprem() {
        return this.relatedLabdiprem;
    }

    public void setRelatedLabdiprem(String relatedLabdiprem) {
        this.relatedLabdiprem = relatedLabdiprem;
    }

    public String getRelatedLabdipLstid() {
        return this.relatedLabdipLstid;
    }

    public void setRelatedLabdipLstid(String relatedLabdipLstid) {
        this.relatedLabdipLstid = relatedLabdipLstid;
    }

    public LocalDateTime getRelatedLabdipLstdate() {
        return this.relatedLabdipLstdate;
    }

    public void setRelatedLabdipLstdate(LocalDateTime relatedLabdipLstdate) {
        this.relatedLabdipLstdate = relatedLabdipLstdate;
    }

    public String getBaseYrnclr() {
        return this.baseYrnclr;
    }

    public void setBaseYrnclr(String baseYrnclr) {
        this.baseYrnclr = baseYrnclr;
    }

    public String getBaseClrref() {
        return this.baseClrref;
    }

    public void setBaseClrref(String baseClrref) {
        this.baseClrref = baseClrref;
    }

    public String getBaseYrncdes() {
        return this.baseYrncdes;
    }

    public void setBaseYrncdes(String baseYrncdes) {
        this.baseYrncdes = baseYrncdes;
    }

    public String getLabtoapp() {
        return this.labtoapp;
    }

    public void setLabtoapp(String labtoapp) {
        this.labtoapp = labtoapp;
    }

    public String getWreqlabdipsts() {
        return this.wreqlabdipsts;
    }

    public void setWreqlabdipsts(String wreqlabdipsts) {
        this.wreqlabdipsts = wreqlabdipsts;
    }

    public String getWlabdipsts() {
        return this.wlabdipsts;
    }

    public void setWlabdipsts(String wlabdipsts) {
        this.wlabdipsts = wlabdipsts;
    }

    public String getWlabdipno() {
        return this.wlabdipno;
    }

    public void setWlabdipno(String wlabdipno) {
        this.wlabdipno = wlabdipno;
    }

    public String getWrevno() {
        return this.wrevno;
    }

    public void setWrevno(String wrevno) {
        this.wrevno = wrevno;
    }

    public String getWaddno() {
        return this.waddno;
    }

    public void setWaddno(String waddno) {
        this.waddno = waddno;
    }

    public String getWpreclrref() {
        return this.wpreclrref;
    }

    public void setWpreclrref(String wpreclrref) {
        this.wpreclrref = wpreclrref;
    }

    public String getWyrncdeslov() {
        return this.wyrncdeslov;
    }

    public void setWyrncdeslov(String wyrncdeslov) {
        this.wyrncdeslov = wyrncdeslov;
    }

    public String getWreqlabdip() {
        return this.wreqlabdip;
    }

    public void setWreqlabdip(String wreqlabdip) {
        this.wreqlabdip = wreqlabdip;
    }

    public String getWapprvlabdip() {
        return this.wapprvlabdip;
    }

    public void setWapprvlabdip(String wapprvlabdip) {
        this.wapprvlabdip = wapprvlabdip;
    }

    public String getYrncnteditacs() {
        return this.yrncnteditacs;
    }

    public void setYrncnteditacs(String yrncnteditacs) {
        this.yrncnteditacs = yrncnteditacs;
    }

    public String getYrncpseditacs() {
        return this.yrncpseditacs;
    }

    public void setYrncpseditacs(String yrncpseditacs) {
        this.yrncpseditacs = yrncpseditacs;
    }

    public String getYrnqltyeditacs() {
        return this.yrnqltyeditacs;
    }

    public void setYrnqltyeditacs(String yrnqltyeditacs) {
        this.yrnqltyeditacs = yrnqltyeditacs;
    }

    public String getYrnsubqltyaeditacs() {
        return this.yrnsubqltyaeditacs;
    }

    public void setYrnsubqltyaeditacs(String yrnsubqltyaeditacs) {
        this.yrnsubqltyaeditacs = yrnsubqltyaeditacs;
    }

    public String getYrnsubqltybeditacs() {
        return this.yrnsubqltybeditacs;
    }

    public void setYrnsubqltybeditacs(String yrnsubqltybeditacs) {
        this.yrnsubqltybeditacs = yrnsubqltybeditacs;
    }

    public String getYrnclreditacs() {
        return this.yrnclreditacs;
    }

    public void setYrnclreditacs(String yrnclreditacs) {
        this.yrnclreditacs = yrnclreditacs;
    }

    public String getYrnffcodeditacs() {
        return this.yrnffcodeditacs;
    }

    public void setYrnffcodeditacs(String yrnffcodeditacs) {
        this.yrnffcodeditacs = yrnffcodeditacs;
    }

    public String getBaseyrnclreditacs() {
        return this.baseyrnclreditacs;
    }

    public void setBaseyrnclreditacs(String baseyrnclreditacs) {
        this.baseyrnclreditacs = baseyrnclreditacs;
    }

    public String getYrnfraceditacs() {
        return this.yrnfraceditacs;
    }

    public void setYrnfraceditacs(String yrnfraceditacs) {
        this.yrnfraceditacs = yrnfraceditacs;
    }

    public String getClrrefeditacs() {
        return this.clrrefeditacs;
    }

    public void setClrrefeditacs(String clrrefeditacs) {
        this.clrrefeditacs = clrrefeditacs;
    }

    public String getOriclreditacs() {
        return this.oriclreditacs;
    }

    public void setOriclreditacs(String oriclreditacs) {
        this.oriclreditacs = oriclreditacs;
    }

    public String getPreclrrefeditacs() {
        return this.preclrrefeditacs;
    }

    public void setPreclrrefeditacs(String preclrrefeditacs) {
        this.preclrrefeditacs = preclrrefeditacs;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or105wpk0qryOrt125ResponsePoutYrnlist)) return false;
        final Or105wpk0qryOrt125ResponsePoutYrnlist or105wpk0qryOrt125responsePoutYrnlist = (Or105wpk0qryOrt125ResponsePoutYrnlist) o;
        return Objects.equals(getOrdnum(), or105wpk0qryOrt125responsePoutYrnlist.getOrdnum()) &&
                Objects.equals(getFabseq(), or105wpk0qryOrt125responsePoutYrnlist.getFabseq()) &&
                Objects.equals(getYrnseq(), or105wpk0qryOrt125responsePoutYrnlist.getYrnseq()) &&
                Objects.equals(getYrncnt(), or105wpk0qryOrt125responsePoutYrnlist.getYrncnt()) &&
                Objects.equals(getYrncps(), or105wpk0qryOrt125responsePoutYrnlist.getYrncps()) &&
                Objects.equals(getYrnclr(), or105wpk0qryOrt125responsePoutYrnlist.getYrnclr()) &&
                Objects.equals(getOriclr(), or105wpk0qryOrt125responsePoutYrnlist.getOriclr()) &&
                Objects.equals(getClrref(), or105wpk0qryOrt125responsePoutYrnlist.getClrref()) &&
                Objects.equals(getWclrrefshadedes(), or105wpk0qryOrt125responsePoutYrnlist.getWclrrefshadedes()) &&
                Objects.equals(getYrnori(), or105wpk0qryOrt125responsePoutYrnlist.getYrnori()) &&
                Objects.equals(getYrnqlty(), or105wpk0qryOrt125responsePoutYrnlist.getYrnqlty()) &&
                Objects.equals(getYrnsubqltya(), or105wpk0qryOrt125responsePoutYrnlist.getYrnsubqltya()) &&
                Objects.equals(getYrnsubqltyb(), or105wpk0qryOrt125responsePoutYrnlist.getYrnsubqltyb()) &&
                Objects.equals(getYrnffcod(), or105wpk0qryOrt125responsePoutYrnlist.getYrnffcod()) &&
                Objects.equals(getWyrnffdesc(), or105wpk0qryOrt125responsePoutYrnlist.getWyrnffdesc()) &&
                Objects.equals(getNumrows(), or105wpk0qryOrt125responsePoutYrnlist.getNumrows()) &&
                Objects.equals(getTotrows(), or105wpk0qryOrt125responsePoutYrnlist.getTotrows()) &&
                Objects.equals(getYrnfrac(), or105wpk0qryOrt125responsePoutYrnlist.getYrnfrac()) &&
                Objects.equals(getTipping(), or105wpk0qryOrt125responsePoutYrnlist.getTipping()) &&
                Objects.equals(getYrnends(), or105wpk0qryOrt125responsePoutYrnlist.getYrnends()) &&
                Objects.equals(getPreclrref(), or105wpk0qryOrt125responsePoutYrnlist.getPreclrref()) &&
                Objects.equals(getInilabdipno(), or105wpk0qryOrt125responsePoutYrnlist.getInilabdipno()) &&
                Objects.equals(getInilabrevno(), or105wpk0qryOrt125responsePoutYrnlist.getInilabrevno()) &&
                Objects.equals(getInilabaddno(), or105wpk0qryOrt125responsePoutYrnlist.getInilabaddno()) &&
                Objects.equals(getInilabapprvdate(), or105wpk0qryOrt125responsePoutYrnlist.getInilabapprvdate()) &&
                Objects.equals(getLabapprvdate(), or105wpk0qryOrt125responsePoutYrnlist.getLabapprvdate()) &&
                Objects.equals(getLabapprvid(), or105wpk0qryOrt125responsePoutYrnlist.getLabapprvid()) &&
                Objects.equals(getRelatedLabdipno(), or105wpk0qryOrt125responsePoutYrnlist.getRelatedLabdipno()) &&
                Objects.equals(getRelatedLabdiprem(), or105wpk0qryOrt125responsePoutYrnlist.getRelatedLabdiprem()) &&
                Objects.equals(getRelatedLabdipLstid(), or105wpk0qryOrt125responsePoutYrnlist.getRelatedLabdipLstid()) &&
                Objects.equals(getRelatedLabdipLstdate(), or105wpk0qryOrt125responsePoutYrnlist.getRelatedLabdipLstdate()) &&
                Objects.equals(getBaseYrnclr(), or105wpk0qryOrt125responsePoutYrnlist.getBaseYrnclr()) &&
                Objects.equals(getBaseClrref(), or105wpk0qryOrt125responsePoutYrnlist.getBaseClrref()) &&
                Objects.equals(getBaseYrncdes(), or105wpk0qryOrt125responsePoutYrnlist.getBaseYrncdes()) &&
                Objects.equals(getLabtoapp(), or105wpk0qryOrt125responsePoutYrnlist.getLabtoapp()) &&
                Objects.equals(getWreqlabdipsts(), or105wpk0qryOrt125responsePoutYrnlist.getWreqlabdipsts()) &&
                Objects.equals(getWlabdipsts(), or105wpk0qryOrt125responsePoutYrnlist.getWlabdipsts()) &&
                Objects.equals(getWlabdipno(), or105wpk0qryOrt125responsePoutYrnlist.getWlabdipno()) &&
                Objects.equals(getWrevno(), or105wpk0qryOrt125responsePoutYrnlist.getWrevno()) &&
                Objects.equals(getWaddno(), or105wpk0qryOrt125responsePoutYrnlist.getWaddno()) &&
                Objects.equals(getWpreclrref(), or105wpk0qryOrt125responsePoutYrnlist.getWpreclrref()) &&
                Objects.equals(getWyrncdeslov(), or105wpk0qryOrt125responsePoutYrnlist.getWyrncdeslov()) &&
                Objects.equals(getWreqlabdip(), or105wpk0qryOrt125responsePoutYrnlist.getWreqlabdip()) &&
                Objects.equals(getWapprvlabdip(), or105wpk0qryOrt125responsePoutYrnlist.getWapprvlabdip()) &&
                Objects.equals(getYrncnteditacs(), or105wpk0qryOrt125responsePoutYrnlist.getYrncnteditacs()) &&
                Objects.equals(getYrncpseditacs(), or105wpk0qryOrt125responsePoutYrnlist.getYrncpseditacs()) &&
                Objects.equals(getYrnqltyeditacs(), or105wpk0qryOrt125responsePoutYrnlist.getYrnqltyeditacs()) &&
                Objects.equals(getYrnsubqltyaeditacs(), or105wpk0qryOrt125responsePoutYrnlist.getYrnsubqltyaeditacs()) &&
                Objects.equals(getYrnsubqltybeditacs(), or105wpk0qryOrt125responsePoutYrnlist.getYrnsubqltybeditacs()) &&
                Objects.equals(getYrnclreditacs(), or105wpk0qryOrt125responsePoutYrnlist.getYrnclreditacs()) &&
                Objects.equals(getYrnffcodeditacs(), or105wpk0qryOrt125responsePoutYrnlist.getYrnffcodeditacs()) &&
                Objects.equals(getBaseyrnclreditacs(), or105wpk0qryOrt125responsePoutYrnlist.getBaseyrnclreditacs()) &&
                Objects.equals(getYrnfraceditacs(), or105wpk0qryOrt125responsePoutYrnlist.getYrnfraceditacs()) &&
                Objects.equals(getClrrefeditacs(), or105wpk0qryOrt125responsePoutYrnlist.getClrrefeditacs()) &&
                Objects.equals(getOriclreditacs(), or105wpk0qryOrt125responsePoutYrnlist.getOriclreditacs()) &&
                Objects.equals(getPreclrrefeditacs(), or105wpk0qryOrt125responsePoutYrnlist.getPreclrrefeditacs());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getFabseq(),
                getYrnseq(),
                getYrncnt(),
                getYrncps(),
                getYrnclr(),
                getOriclr(),
                getClrref(),
                getWclrrefshadedes(),
                getYrnori(),
                getYrnqlty(),
                getYrnsubqltya(),
                getYrnsubqltyb(),
                getYrnffcod(),
                getWyrnffdesc(),
                getNumrows(),
                getTotrows(),
                getYrnfrac(),
                getTipping(),
                getYrnends(),
                getPreclrref(),
                getInilabdipno(),
                getInilabrevno(),
                getInilabaddno(),
                getInilabapprvdate(),
                getLabapprvdate(),
                getLabapprvid(),
                getRelatedLabdipno(),
                getRelatedLabdiprem(),
                getRelatedLabdipLstid(),
                getRelatedLabdipLstdate(),
                getBaseYrnclr(),
                getBaseClrref(),
                getBaseYrncdes(),
                getLabtoapp(),
                getWreqlabdipsts(),
                getWlabdipsts(),
                getWlabdipno(),
                getWrevno(),
                getWaddno(),
                getWpreclrref(),
                getWyrncdeslov(),
                getWreqlabdip(),
                getWapprvlabdip(),
                getYrncnteditacs(),
                getYrncpseditacs(),
                getYrnqltyeditacs(),
                getYrnsubqltyaeditacs(),
                getYrnsubqltybeditacs(),
                getYrnclreditacs(),
                getYrnffcodeditacs(),
                getBaseyrnclreditacs(),
                getYrnfraceditacs(),
                getClrrefeditacs(),
                getOriclreditacs(),
                getPreclrrefeditacs());
    }
}