/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or105wpk0yrnGetyrncpsResponse implements Serializable {


    @ColumnAlias("poutYrncps")
    private List<Or105wpk0yrnGetyrncpsResponsePoutYrncps> poutYrncps;

    public List<Or105wpk0yrnGetyrncpsResponsePoutYrncps> getPoutYrncps() {
        return this.poutYrncps;
    }

    public void setPoutYrncps(List<Or105wpk0yrnGetyrncpsResponsePoutYrncps> poutYrncps) {
        this.poutYrncps = poutYrncps;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or105wpk0yrnGetyrncpsResponse)) return false;
        final Or105wpk0yrnGetyrncpsResponse or105wpk0yrnGetyrncpsResponse = (Or105wpk0yrnGetyrncpsResponse) o;
        return Objects.equals(getPoutYrncps(), or105wpk0yrnGetyrncpsResponse.getPoutYrncps());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutYrncps());
    }
}