/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or105wpk0yrnGetYrnffcodResponse implements Serializable {


    @ColumnAlias("poutYrnffcod")
    private List<Or105wpk0yrnGetYrnffcodResponsePoutYrnffcod> poutYrnffcod;

    public List<Or105wpk0yrnGetYrnffcodResponsePoutYrnffcod> getPoutYrnffcod() {
        return this.poutYrnffcod;
    }

    public void setPoutYrnffcod(List<Or105wpk0yrnGetYrnffcodResponsePoutYrnffcod> poutYrnffcod) {
        this.poutYrnffcod = poutYrnffcod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or105wpk0yrnGetYrnffcodResponse)) return false;
        final Or105wpk0yrnGetYrnffcodResponse or105wpk0yrnGetYrnffcodResponse = (Or105wpk0yrnGetYrnffcodResponse) o;
        return Objects.equals(getPoutYrnffcod(), or105wpk0yrnGetYrnffcodResponse.getPoutYrnffcod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutYrnffcod());
    }
}