/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or105wpk0YrnValRecordOrt125Response implements Serializable {


    @ColumnAlias("poutNewrow")
    private String poutNewrow;

    @ColumnAlias("pWarnmsg")
    private String pwarnmsg;

    public String getPoutNewrow() {
        return this.poutNewrow;
    }

    public void setPoutNewrow(String poutNewrow) {
        this.poutNewrow = poutNewrow;
    }

    public String getPwarnmsg() {
        return this.pwarnmsg;
    }

    public void setPwarnmsg(String pwarnmsg) {
        this.pwarnmsg = pwarnmsg;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or105wpk0YrnValRecordOrt125Response)) return false;
        final Or105wpk0YrnValRecordOrt125Response or105wpk0yrnValRecordOrt125response = (Or105wpk0YrnValRecordOrt125Response) o;
        return Objects.equals(getPoutNewrow(), or105wpk0yrnValRecordOrt125response.getPoutNewrow()) &&
                Objects.equals(getPwarnmsg(), or105wpk0yrnValRecordOrt125response.getPwarnmsg());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutNewrow(),
                getPwarnmsg());
    }
}