/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or105wpk0yrnGetyrncntResponse implements Serializable {


    @ColumnAlias("poutYrncnt")
    private List<Or105wpk0yrnGetyrncntResponsePoutYrncnt> poutYrncnt;

    public List<Or105wpk0yrnGetyrncntResponsePoutYrncnt> getPoutYrncnt() {
        return this.poutYrncnt;
    }

    public void setPoutYrncnt(List<Or105wpk0yrnGetyrncntResponsePoutYrncnt> poutYrncnt) {
        this.poutYrncnt = poutYrncnt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or105wpk0yrnGetyrncntResponse)) return false;
        final Or105wpk0yrnGetyrncntResponse or105wpk0yrnGetyrncntResponse = (Or105wpk0yrnGetyrncntResponse) o;
        return Objects.equals(getPoutYrncnt(), or105wpk0yrnGetyrncntResponse.getPoutYrncnt());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutYrncnt());
    }
}