/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or207pk0fetchExtranetDetailsResponse implements Serializable {


    @ColumnAlias("pOutWarningMsg")
    private String poutWarningMsg;

    public String getPoutWarningMsg() {
        return this.poutWarningMsg;
    }

    public void setPoutWarningMsg(String poutWarningMsg) {
        this.poutWarningMsg = poutWarningMsg;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or207pk0fetchExtranetDetailsResponse)) return false;
        final Or207pk0fetchExtranetDetailsResponse or207pk0fetchExtranetDetailsResponse = (Or207pk0fetchExtranetDetailsResponse) o;
        return Objects.equals(getPoutWarningMsg(), or207pk0fetchExtranetDetailsResponse.getPoutWarningMsg());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutWarningMsg());
    }
}