/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or207pk0searchOrdRefResponse implements Serializable {


    @ColumnAlias("poutOrderList")
    private List<Or207pk0searchOrdRefResponsePoutOrderList> poutOrderList;

    public List<Or207pk0searchOrdRefResponsePoutOrderList> getPoutOrderList() {
        return this.poutOrderList;
    }

    public void setPoutOrderList(List<Or207pk0searchOrdRefResponsePoutOrderList> poutOrderList) {
        this.poutOrderList = poutOrderList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or207pk0searchOrdRefResponse)) return false;
        final Or207pk0searchOrdRefResponse or207pk0searchOrdRefResponse = (Or207pk0searchOrdRefResponse) o;
        return Objects.equals(getPoutOrderList(), or207pk0searchOrdRefResponse.getPoutOrderList());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutOrderList());
    }
}