/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or207pk0getCmtPriceChgHistoryResponse implements Serializable {


    @ColumnAlias("pOutOrt207PrcChgHist")
    private List<Or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist> poutOrt207prcChgHist;

    @ColumnAlias("pOutShowFliprcInd")
    private String poutShowFliprcInd;

    @ColumnAlias("pOutShowRetprcbInd")
    private String poutShowRetprcbInd;

    @ColumnAlias("pOutShowRetprccInd")
    private String poutShowRetprccInd;

    @ColumnAlias("pOutShowRetprcdInd")
    private String poutShowRetprcdInd;

    public List<Or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist> getPoutOrt207prcChgHist() {
        return this.poutOrt207prcChgHist;
    }

    public void setPoutOrt207prcChgHist(List<Or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist> poutOrt207prcChgHist) {
        this.poutOrt207prcChgHist = poutOrt207prcChgHist;
    }

    public String getPoutShowFliprcInd() {
        return this.poutShowFliprcInd;
    }

    public void setPoutShowFliprcInd(String poutShowFliprcInd) {
        this.poutShowFliprcInd = poutShowFliprcInd;
    }

    public String getPoutShowRetprcbInd() {
        return this.poutShowRetprcbInd;
    }

    public void setPoutShowRetprcbInd(String poutShowRetprcbInd) {
        this.poutShowRetprcbInd = poutShowRetprcbInd;
    }

    public String getPoutShowRetprccInd() {
        return this.poutShowRetprccInd;
    }

    public void setPoutShowRetprccInd(String poutShowRetprccInd) {
        this.poutShowRetprccInd = poutShowRetprccInd;
    }

    public String getPoutShowRetprcdInd() {
        return this.poutShowRetprcdInd;
    }

    public void setPoutShowRetprcdInd(String poutShowRetprcdInd) {
        this.poutShowRetprcdInd = poutShowRetprcdInd;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or207pk0getCmtPriceChgHistoryResponse)) return false;
        final Or207pk0getCmtPriceChgHistoryResponse or207pk0getCmtPriceChgHistoryResponse = (Or207pk0getCmtPriceChgHistoryResponse) o;
        return Objects.equals(getPoutOrt207prcChgHist(), or207pk0getCmtPriceChgHistoryResponse.getPoutOrt207prcChgHist()) &&
                Objects.equals(getPoutShowFliprcInd(), or207pk0getCmtPriceChgHistoryResponse.getPoutShowFliprcInd()) &&
                Objects.equals(getPoutShowRetprcbInd(), or207pk0getCmtPriceChgHistoryResponse.getPoutShowRetprcbInd()) &&
                Objects.equals(getPoutShowRetprccInd(), or207pk0getCmtPriceChgHistoryResponse.getPoutShowRetprccInd()) &&
                Objects.equals(getPoutShowRetprcdInd(), or207pk0getCmtPriceChgHistoryResponse.getPoutShowRetprcdInd());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutOrt207prcChgHist(),
                getPoutShowFliprcInd(),
                getPoutShowRetprcbInd(),
                getPoutShowRetprccInd(),
                getPoutShowRetprcdInd());
    }
}