/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or207pk0getOrt205recordResponse implements Serializable {


    @ColumnAlias("pOutShpDet")
    private List<Or207pk0getOrt205recordResponsePoutShpDet> poutShpDet;

    public List<Or207pk0getOrt205recordResponsePoutShpDet> getPoutShpDet() {
        return this.poutShpDet;
    }

    public void setPoutShpDet(List<Or207pk0getOrt205recordResponsePoutShpDet> poutShpDet) {
        this.poutShpDet = poutShpDet;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or207pk0getOrt205recordResponse)) return false;
        final Or207pk0getOrt205recordResponse or207pk0getOrt205recordResponse = (Or207pk0getOrt205recordResponse) o;
        return Objects.equals(getPoutShpDet(), or207pk0getOrt205recordResponse.getPoutShpDet());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutShpDet());
    }
}