/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("SEQCOD")
    private String seqcod;

    @ColumnAlias("WPCKDES")
    private String wpckdes;

    @ColumnAlias("SZESEQ")
    private Byte szeseq;

    @ColumnAlias("WSZEDES")
    private String wszedes;

    @ColumnAlias("CLIONUM")
    private String clionum;

    @ColumnAlias("PRICECAT")
    private String pricecat;

    @ColumnAlias("AUDSEQ")
    private Short audseq;

    @ColumnAlias("CHGREASON")
    private String chgreason;

    @ColumnAlias("CHGREASONDES")
    private String chgreasondes;

    @ColumnAlias("OLDUNTPRC_AIR")
    private Double olduntprcAir;

    @ColumnAlias("REVUNTPRC_AIR")
    private Double revuntprcAir;

    @ColumnAlias("OLDUNTPRC_SEA")
    private Double olduntprcSea;

    @ColumnAlias("REVUNTPRC_SEA")
    private Double revuntprcSea;

    @ColumnAlias("OLDDISCOUNTPRC_AIR")
    private Double olddiscountprcAir;

    @ColumnAlias("REVDISCOUNTPRC_AIR")
    private Double revdiscountprcAir;

    @ColumnAlias("OLDDISCOUNTPRC_SEA")
    private Double olddiscountprcSea;

    @ColumnAlias("REVDISCOUNTPRC_SEA")
    private Double revdiscountprcSea;

    @ColumnAlias("OLDDISCOUNTCODE")
    private String olddiscountcode;

    @ColumnAlias("REVDISCOUNTCODE")
    private String revdiscountcode;

    @ColumnAlias("OLDFLIPRC_AIR")
    private Double oldfliprcAir;

    @ColumnAlias("REVFLIPRC_AIR")
    private Double revfliprcAir;

    @ColumnAlias("OLDFLIPRC_SEA")
    private Double oldfliprcSea;

    @ColumnAlias("REVFLIPRC_SEA")
    private Double revfliprcSea;

    @ColumnAlias("OLDRETPRC")
    private Double oldretprc;

    @ColumnAlias("REVRETPRC")
    private Double revretprc;

    @ColumnAlias("OLDRETPRCB")
    private Double oldretprcb;

    @ColumnAlias("REVRETPRCB")
    private Double revretprcb;

    @ColumnAlias("OLDRETPRCC")
    private Double oldretprcc;

    @ColumnAlias("REVRETPRCC")
    private Double revretprcc;

    @ColumnAlias("OLDRETPRCD")
    private Double oldretprcd;

    @ColumnAlias("REVRETPRCD")
    private Double revretprcd;

    @ColumnAlias("PRGNAME")
    private String prgname;

    @ColumnAlias("USRID")
    private String usrid;

    @ColumnAlias("USRNAME")
    private String usrname;

    @ColumnAlias("ENTDAT")
    private LocalDateTime entdat;

    @ColumnAlias("REMARKS")
    private String remarks;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getSeqcod() {
        return this.seqcod;
    }

    public void setSeqcod(String seqcod) {
        this.seqcod = seqcod;
    }

    public String getWpckdes() {
        return this.wpckdes;
    }

    public void setWpckdes(String wpckdes) {
        this.wpckdes = wpckdes;
    }

    public Byte getSzeseq() {
        return this.szeseq;
    }

    public void setSzeseq(Byte szeseq) {
        this.szeseq = szeseq;
    }

    public String getWszedes() {
        return this.wszedes;
    }

    public void setWszedes(String wszedes) {
        this.wszedes = wszedes;
    }

    public String getClionum() {
        return this.clionum;
    }

    public void setClionum(String clionum) {
        this.clionum = clionum;
    }

    public String getPricecat() {
        return this.pricecat;
    }

    public void setPricecat(String pricecat) {
        this.pricecat = pricecat;
    }

    public Short getAudseq() {
        return this.audseq;
    }

    public void setAudseq(Short audseq) {
        this.audseq = audseq;
    }

    public String getChgreason() {
        return this.chgreason;
    }

    public void setChgreason(String chgreason) {
        this.chgreason = chgreason;
    }

    public String getChgreasondes() {
        return this.chgreasondes;
    }

    public void setChgreasondes(String chgreasondes) {
        this.chgreasondes = chgreasondes;
    }

    public Double getOlduntprcAir() {
        return this.olduntprcAir;
    }

    public void setOlduntprcAir(Double olduntprcAir) {
        this.olduntprcAir = olduntprcAir;
    }

    public Double getRevuntprcAir() {
        return this.revuntprcAir;
    }

    public void setRevuntprcAir(Double revuntprcAir) {
        this.revuntprcAir = revuntprcAir;
    }

    public Double getOlduntprcSea() {
        return this.olduntprcSea;
    }

    public void setOlduntprcSea(Double olduntprcSea) {
        this.olduntprcSea = olduntprcSea;
    }

    public Double getRevuntprcSea() {
        return this.revuntprcSea;
    }

    public void setRevuntprcSea(Double revuntprcSea) {
        this.revuntprcSea = revuntprcSea;
    }

    public Double getOlddiscountprcAir() {
        return this.olddiscountprcAir;
    }

    public void setOlddiscountprcAir(Double olddiscountprcAir) {
        this.olddiscountprcAir = olddiscountprcAir;
    }

    public Double getRevdiscountprcAir() {
        return this.revdiscountprcAir;
    }

    public void setRevdiscountprcAir(Double revdiscountprcAir) {
        this.revdiscountprcAir = revdiscountprcAir;
    }

    public Double getOlddiscountprcSea() {
        return this.olddiscountprcSea;
    }

    public void setOlddiscountprcSea(Double olddiscountprcSea) {
        this.olddiscountprcSea = olddiscountprcSea;
    }

    public Double getRevdiscountprcSea() {
        return this.revdiscountprcSea;
    }

    public void setRevdiscountprcSea(Double revdiscountprcSea) {
        this.revdiscountprcSea = revdiscountprcSea;
    }

    public String getOlddiscountcode() {
        return this.olddiscountcode;
    }

    public void setOlddiscountcode(String olddiscountcode) {
        this.olddiscountcode = olddiscountcode;
    }

    public String getRevdiscountcode() {
        return this.revdiscountcode;
    }

    public void setRevdiscountcode(String revdiscountcode) {
        this.revdiscountcode = revdiscountcode;
    }

    public Double getOldfliprcAir() {
        return this.oldfliprcAir;
    }

    public void setOldfliprcAir(Double oldfliprcAir) {
        this.oldfliprcAir = oldfliprcAir;
    }

    public Double getRevfliprcAir() {
        return this.revfliprcAir;
    }

    public void setRevfliprcAir(Double revfliprcAir) {
        this.revfliprcAir = revfliprcAir;
    }

    public Double getOldfliprcSea() {
        return this.oldfliprcSea;
    }

    public void setOldfliprcSea(Double oldfliprcSea) {
        this.oldfliprcSea = oldfliprcSea;
    }

    public Double getRevfliprcSea() {
        return this.revfliprcSea;
    }

    public void setRevfliprcSea(Double revfliprcSea) {
        this.revfliprcSea = revfliprcSea;
    }

    public Double getOldretprc() {
        return this.oldretprc;
    }

    public void setOldretprc(Double oldretprc) {
        this.oldretprc = oldretprc;
    }

    public Double getRevretprc() {
        return this.revretprc;
    }

    public void setRevretprc(Double revretprc) {
        this.revretprc = revretprc;
    }

    public Double getOldretprcb() {
        return this.oldretprcb;
    }

    public void setOldretprcb(Double oldretprcb) {
        this.oldretprcb = oldretprcb;
    }

    public Double getRevretprcb() {
        return this.revretprcb;
    }

    public void setRevretprcb(Double revretprcb) {
        this.revretprcb = revretprcb;
    }

    public Double getOldretprcc() {
        return this.oldretprcc;
    }

    public void setOldretprcc(Double oldretprcc) {
        this.oldretprcc = oldretprcc;
    }

    public Double getRevretprcc() {
        return this.revretprcc;
    }

    public void setRevretprcc(Double revretprcc) {
        this.revretprcc = revretprcc;
    }

    public Double getOldretprcd() {
        return this.oldretprcd;
    }

    public void setOldretprcd(Double oldretprcd) {
        this.oldretprcd = oldretprcd;
    }

    public Double getRevretprcd() {
        return this.revretprcd;
    }

    public void setRevretprcd(Double revretprcd) {
        this.revretprcd = revretprcd;
    }

    public String getPrgname() {
        return this.prgname;
    }

    public void setPrgname(String prgname) {
        this.prgname = prgname;
    }

    public String getUsrid() {
        return this.usrid;
    }

    public void setUsrid(String usrid) {
        this.usrid = usrid;
    }

    public String getUsrname() {
        return this.usrname;
    }

    public void setUsrname(String usrname) {
        this.usrname = usrname;
    }

    public LocalDateTime getEntdat() {
        return this.entdat;
    }

    public void setEntdat(LocalDateTime entdat) {
        this.entdat = entdat;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist)) return false;
        final Or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist = (Or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist) o;
        return Objects.equals(getOrdnum(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOrdnum()) &&
                Objects.equals(getSeqcod(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getSeqcod()) &&
                Objects.equals(getWpckdes(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getWpckdes()) &&
                Objects.equals(getSzeseq(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getSzeseq()) &&
                Objects.equals(getWszedes(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getWszedes()) &&
                Objects.equals(getClionum(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getClionum()) &&
                Objects.equals(getPricecat(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getPricecat()) &&
                Objects.equals(getAudseq(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getAudseq()) &&
                Objects.equals(getChgreason(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getChgreason()) &&
                Objects.equals(getChgreasondes(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getChgreasondes()) &&
                Objects.equals(getOlduntprcAir(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOlduntprcAir()) &&
                Objects.equals(getRevuntprcAir(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRevuntprcAir()) &&
                Objects.equals(getOlduntprcSea(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOlduntprcSea()) &&
                Objects.equals(getRevuntprcSea(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRevuntprcSea()) &&
                Objects.equals(getOlddiscountprcAir(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOlddiscountprcAir()) &&
                Objects.equals(getRevdiscountprcAir(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRevdiscountprcAir()) &&
                Objects.equals(getOlddiscountprcSea(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOlddiscountprcSea()) &&
                Objects.equals(getRevdiscountprcSea(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRevdiscountprcSea()) &&
                Objects.equals(getOlddiscountcode(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOlddiscountcode()) &&
                Objects.equals(getRevdiscountcode(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRevdiscountcode()) &&
                Objects.equals(getOldfliprcAir(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOldfliprcAir()) &&
                Objects.equals(getRevfliprcAir(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRevfliprcAir()) &&
                Objects.equals(getOldfliprcSea(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOldfliprcSea()) &&
                Objects.equals(getRevfliprcSea(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRevfliprcSea()) &&
                Objects.equals(getOldretprc(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOldretprc()) &&
                Objects.equals(getRevretprc(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRevretprc()) &&
                Objects.equals(getOldretprcb(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOldretprcb()) &&
                Objects.equals(getRevretprcb(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRevretprcb()) &&
                Objects.equals(getOldretprcc(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOldretprcc()) &&
                Objects.equals(getRevretprcc(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRevretprcc()) &&
                Objects.equals(getOldretprcd(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getOldretprcd()) &&
                Objects.equals(getRevretprcd(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRevretprcd()) &&
                Objects.equals(getPrgname(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getPrgname()) &&
                Objects.equals(getUsrid(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getUsrid()) &&
                Objects.equals(getUsrname(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getUsrname()) &&
                Objects.equals(getEntdat(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getEntdat()) &&
                Objects.equals(getRemarks(), or207pk0getCmtPriceChgHistoryResponsePoutOrt207prcChgHist.getRemarks());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getSeqcod(),
                getWpckdes(),
                getSzeseq(),
                getWszedes(),
                getClionum(),
                getPricecat(),
                getAudseq(),
                getChgreason(),
                getChgreasondes(),
                getOlduntprcAir(),
                getRevuntprcAir(),
                getOlduntprcSea(),
                getRevuntprcSea(),
                getOlddiscountprcAir(),
                getRevdiscountprcAir(),
                getOlddiscountprcSea(),
                getRevdiscountprcSea(),
                getOlddiscountcode(),
                getRevdiscountcode(),
                getOldfliprcAir(),
                getRevfliprcAir(),
                getOldfliprcSea(),
                getRevfliprcSea(),
                getOldretprc(),
                getRevretprc(),
                getOldretprcb(),
                getRevretprcb(),
                getOldretprcc(),
                getRevretprcc(),
                getOldretprcd(),
                getRevretprcd(),
                getPrgname(),
                getUsrid(),
                getUsrname(),
                getEntdat(),
                getRemarks());
    }
}