/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or207pk0getOrt209recordResponsePoutDetShp implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("SEQCOD")
    private String seqcod;

    @ColumnAlias("SHPNUM")
    private String shpnum;

    @ColumnAlias("SZESEQ")
    private Byte szeseq;

    @ColumnAlias("UNTPRC")
    private Double untprc;

    @ColumnAlias("QTYORD")
    private Integer qtyord;

    @ColumnAlias("INTUNTPRC")
    private BigDecimal intuntprc;

    @ColumnAlias("FLIPRC")
    private Double fliprc;

    @ColumnAlias("INTFLIPRC")
    private BigDecimal intfliprc;

    @ColumnAlias("RETPRC")
    private Double retprc;

    @ColumnAlias("RETPRCB")
    private Double retprcb;

    @ColumnAlias("RETPRCC")
    private Double retprcc;

    @ColumnAlias("RETPRCD")
    private Double retprcd;

    @ColumnAlias("DISCOUNTPRC")
    private Double discountprc;

    @ColumnAlias("DISCOUNTCODE")
    private String discountcode;

    @ColumnAlias("INTDISCOUNTPRC")
    private BigDecimal intdiscountprc;

    @ColumnAlias("INTRETPRC")
    private BigDecimal intretprc;

    @ColumnAlias("INTRETPRCB")
    private BigDecimal intretprcb;

    @ColumnAlias("INTRETPRCC")
    private BigDecimal intretprcc;

    @ColumnAlias("INTRETPRCD")
    private BigDecimal intretprcd;

    @ColumnAlias("WPCKDES")
    private String wpckdes;

    @ColumnAlias("WSZEDES")
    private String wszedes;

    @ColumnAlias("WDISCOUNTREASON")
    private String wdiscountreason;

    @ColumnAlias("WLINENO")
    private String wlineno;

    @ColumnAlias("WFINPRICE")
    private BigDecimal wfinprice;

    @ColumnAlias("WINTFINPRICE")
    private BigDecimal wintfinprice;

    @ColumnAlias("WCLIONUM")
    private String wclionum;

    @ColumnAlias("REF")
    private String ref;

    @ColumnAlias("REF2")
    private String ref2;

    @ColumnAlias("REF3")
    private String ref3;

    @ColumnAlias("REF4")
    private String ref4;

    @ColumnAlias("REF5")
    private String ref5;

    @ColumnAlias("REF6")
    private String ref6;

    @ColumnAlias("REF7")
    private String ref7;

    @ColumnAlias("REF8")
    private String ref8;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getSeqcod() {
        return this.seqcod;
    }

    public void setSeqcod(String seqcod) {
        this.seqcod = seqcod;
    }

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    public Byte getSzeseq() {
        return this.szeseq;
    }

    public void setSzeseq(Byte szeseq) {
        this.szeseq = szeseq;
    }

    public Double getUntprc() {
        return this.untprc;
    }

    public void setUntprc(Double untprc) {
        this.untprc = untprc;
    }

    public Integer getQtyord() {
        return this.qtyord;
    }

    public void setQtyord(Integer qtyord) {
        this.qtyord = qtyord;
    }

    public BigDecimal getIntuntprc() {
        return this.intuntprc;
    }

    public void setIntuntprc(BigDecimal intuntprc) {
        this.intuntprc = intuntprc;
    }

    public Double getFliprc() {
        return this.fliprc;
    }

    public void setFliprc(Double fliprc) {
        this.fliprc = fliprc;
    }

    public BigDecimal getIntfliprc() {
        return this.intfliprc;
    }

    public void setIntfliprc(BigDecimal intfliprc) {
        this.intfliprc = intfliprc;
    }

    public Double getRetprc() {
        return this.retprc;
    }

    public void setRetprc(Double retprc) {
        this.retprc = retprc;
    }

    public Double getRetprcb() {
        return this.retprcb;
    }

    public void setRetprcb(Double retprcb) {
        this.retprcb = retprcb;
    }

    public Double getRetprcc() {
        return this.retprcc;
    }

    public void setRetprcc(Double retprcc) {
        this.retprcc = retprcc;
    }

    public Double getRetprcd() {
        return this.retprcd;
    }

    public void setRetprcd(Double retprcd) {
        this.retprcd = retprcd;
    }

    public Double getDiscountprc() {
        return this.discountprc;
    }

    public void setDiscountprc(Double discountprc) {
        this.discountprc = discountprc;
    }

    public String getDiscountcode() {
        return this.discountcode;
    }

    public void setDiscountcode(String discountcode) {
        this.discountcode = discountcode;
    }

    public BigDecimal getIntdiscountprc() {
        return this.intdiscountprc;
    }

    public void setIntdiscountprc(BigDecimal intdiscountprc) {
        this.intdiscountprc = intdiscountprc;
    }

    public BigDecimal getIntretprc() {
        return this.intretprc;
    }

    public void setIntretprc(BigDecimal intretprc) {
        this.intretprc = intretprc;
    }

    public BigDecimal getIntretprcb() {
        return this.intretprcb;
    }

    public void setIntretprcb(BigDecimal intretprcb) {
        this.intretprcb = intretprcb;
    }

    public BigDecimal getIntretprcc() {
        return this.intretprcc;
    }

    public void setIntretprcc(BigDecimal intretprcc) {
        this.intretprcc = intretprcc;
    }

    public BigDecimal getIntretprcd() {
        return this.intretprcd;
    }

    public void setIntretprcd(BigDecimal intretprcd) {
        this.intretprcd = intretprcd;
    }

    public String getWpckdes() {
        return this.wpckdes;
    }

    public void setWpckdes(String wpckdes) {
        this.wpckdes = wpckdes;
    }

    public String getWszedes() {
        return this.wszedes;
    }

    public void setWszedes(String wszedes) {
        this.wszedes = wszedes;
    }

    public String getWdiscountreason() {
        return this.wdiscountreason;
    }

    public void setWdiscountreason(String wdiscountreason) {
        this.wdiscountreason = wdiscountreason;
    }

    public String getWlineno() {
        return this.wlineno;
    }

    public void setWlineno(String wlineno) {
        this.wlineno = wlineno;
    }

    public BigDecimal getWfinprice() {
        return this.wfinprice;
    }

    public void setWfinprice(BigDecimal wfinprice) {
        this.wfinprice = wfinprice;
    }

    public BigDecimal getWintfinprice() {
        return this.wintfinprice;
    }

    public void setWintfinprice(BigDecimal wintfinprice) {
        this.wintfinprice = wintfinprice;
    }

    public String getWclionum() {
        return this.wclionum;
    }

    public void setWclionum(String wclionum) {
        this.wclionum = wclionum;
    }

    public String getRef() {
        return this.ref;
    }

    public void setRef(String ref) {
        this.ref = ref;
    }

    public String getRef2() {
        return this.ref2;
    }

    public void setRef2(String ref2) {
        this.ref2 = ref2;
    }

    public String getRef3() {
        return this.ref3;
    }

    public void setRef3(String ref3) {
        this.ref3 = ref3;
    }

    public String getRef4() {
        return this.ref4;
    }

    public void setRef4(String ref4) {
        this.ref4 = ref4;
    }

    public String getRef5() {
        return this.ref5;
    }

    public void setRef5(String ref5) {
        this.ref5 = ref5;
    }

    public String getRef6() {
        return this.ref6;
    }

    public void setRef6(String ref6) {
        this.ref6 = ref6;
    }

    public String getRef7() {
        return this.ref7;
    }

    public void setRef7(String ref7) {
        this.ref7 = ref7;
    }

    public String getRef8() {
        return this.ref8;
    }

    public void setRef8(String ref8) {
        this.ref8 = ref8;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or207pk0getOrt209recordResponsePoutDetShp)) return false;
        final Or207pk0getOrt209recordResponsePoutDetShp or207pk0getOrt209recordResponsePoutDetShp = (Or207pk0getOrt209recordResponsePoutDetShp) o;
        return Objects.equals(getOrdnum(), or207pk0getOrt209recordResponsePoutDetShp.getOrdnum()) &&
                Objects.equals(getSeqcod(), or207pk0getOrt209recordResponsePoutDetShp.getSeqcod()) &&
                Objects.equals(getShpnum(), or207pk0getOrt209recordResponsePoutDetShp.getShpnum()) &&
                Objects.equals(getSzeseq(), or207pk0getOrt209recordResponsePoutDetShp.getSzeseq()) &&
                Objects.equals(getUntprc(), or207pk0getOrt209recordResponsePoutDetShp.getUntprc()) &&
                Objects.equals(getQtyord(), or207pk0getOrt209recordResponsePoutDetShp.getQtyord()) &&
                Objects.equals(getIntuntprc(), or207pk0getOrt209recordResponsePoutDetShp.getIntuntprc()) &&
                Objects.equals(getFliprc(), or207pk0getOrt209recordResponsePoutDetShp.getFliprc()) &&
                Objects.equals(getIntfliprc(), or207pk0getOrt209recordResponsePoutDetShp.getIntfliprc()) &&
                Objects.equals(getRetprc(), or207pk0getOrt209recordResponsePoutDetShp.getRetprc()) &&
                Objects.equals(getRetprcb(), or207pk0getOrt209recordResponsePoutDetShp.getRetprcb()) &&
                Objects.equals(getRetprcc(), or207pk0getOrt209recordResponsePoutDetShp.getRetprcc()) &&
                Objects.equals(getRetprcd(), or207pk0getOrt209recordResponsePoutDetShp.getRetprcd()) &&
                Objects.equals(getDiscountprc(), or207pk0getOrt209recordResponsePoutDetShp.getDiscountprc()) &&
                Objects.equals(getDiscountcode(), or207pk0getOrt209recordResponsePoutDetShp.getDiscountcode()) &&
                Objects.equals(getIntdiscountprc(), or207pk0getOrt209recordResponsePoutDetShp.getIntdiscountprc()) &&
                Objects.equals(getIntretprc(), or207pk0getOrt209recordResponsePoutDetShp.getIntretprc()) &&
                Objects.equals(getIntretprcb(), or207pk0getOrt209recordResponsePoutDetShp.getIntretprcb()) &&
                Objects.equals(getIntretprcc(), or207pk0getOrt209recordResponsePoutDetShp.getIntretprcc()) &&
                Objects.equals(getIntretprcd(), or207pk0getOrt209recordResponsePoutDetShp.getIntretprcd()) &&
                Objects.equals(getWpckdes(), or207pk0getOrt209recordResponsePoutDetShp.getWpckdes()) &&
                Objects.equals(getWszedes(), or207pk0getOrt209recordResponsePoutDetShp.getWszedes()) &&
                Objects.equals(getWdiscountreason(), or207pk0getOrt209recordResponsePoutDetShp.getWdiscountreason()) &&
                Objects.equals(getWlineno(), or207pk0getOrt209recordResponsePoutDetShp.getWlineno()) &&
                Objects.equals(getWfinprice(), or207pk0getOrt209recordResponsePoutDetShp.getWfinprice()) &&
                Objects.equals(getWintfinprice(), or207pk0getOrt209recordResponsePoutDetShp.getWintfinprice()) &&
                Objects.equals(getWclionum(), or207pk0getOrt209recordResponsePoutDetShp.getWclionum()) &&
                Objects.equals(getRef(), or207pk0getOrt209recordResponsePoutDetShp.getRef()) &&
                Objects.equals(getRef2(), or207pk0getOrt209recordResponsePoutDetShp.getRef2()) &&
                Objects.equals(getRef3(), or207pk0getOrt209recordResponsePoutDetShp.getRef3()) &&
                Objects.equals(getRef4(), or207pk0getOrt209recordResponsePoutDetShp.getRef4()) &&
                Objects.equals(getRef5(), or207pk0getOrt209recordResponsePoutDetShp.getRef5()) &&
                Objects.equals(getRef6(), or207pk0getOrt209recordResponsePoutDetShp.getRef6()) &&
                Objects.equals(getRef7(), or207pk0getOrt209recordResponsePoutDetShp.getRef7()) &&
                Objects.equals(getRef8(), or207pk0getOrt209recordResponsePoutDetShp.getRef8());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getSeqcod(),
                getShpnum(),
                getSzeseq(),
                getUntprc(),
                getQtyord(),
                getIntuntprc(),
                getFliprc(),
                getIntfliprc(),
                getRetprc(),
                getRetprcb(),
                getRetprcc(),
                getRetprcd(),
                getDiscountprc(),
                getDiscountcode(),
                getIntdiscountprc(),
                getIntretprc(),
                getIntretprcb(),
                getIntretprcc(),
                getIntretprcd(),
                getWpckdes(),
                getWszedes(),
                getWdiscountreason(),
                getWlineno(),
                getWfinprice(),
                getWintfinprice(),
                getWclionum(),
                getRef(),
                getRef2(),
                getRef3(),
                getRef4(),
                getRef5(),
                getRef6(),
                getRef7(),
                getRef8());
    }
}