/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Or207pk0getChgReasonResponse implements Serializable {


    @ColumnAlias("pOutLovChgReason")
    private List<Or207pk0getChgReasonResponsePoutLovChgReason> poutLovChgReason;

    public List<Or207pk0getChgReasonResponsePoutLovChgReason> getPoutLovChgReason() {
        return this.poutLovChgReason;
    }

    public void setPoutLovChgReason(List<Or207pk0getChgReasonResponsePoutLovChgReason> poutLovChgReason) {
        this.poutLovChgReason = poutLovChgReason;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Or207pk0getChgReasonResponse)) return false;
        final Or207pk0getChgReasonResponse or207pk0getChgReasonResponse = (Or207pk0getChgReasonResponse) o;
        return Objects.equals(getPoutLovChgReason(), or207pk0getChgReasonResponse.getPoutLovChgReason());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutLovChgReason());
    }
}