/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcOr105pk0CpyfabgetMarkertypeLovResponsePoutListMarkertyp implements Serializable {


    @ColumnAlias("ITEMCOD")
    private String itemcod;

    @ColumnAlias("MARKERTYPDES")
    private String markertypdes;

    public String getItemcod() {
        return this.itemcod;
    }

    public void setItemcod(String itemcod) {
        this.itemcod = itemcod;
    }

    public String getMarkertypdes() {
        return this.markertypdes;
    }

    public void setMarkertypdes(String markertypdes) {
        this.markertypdes = markertypdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcOr105pk0CpyfabgetMarkertypeLovResponsePoutListMarkertyp)) return false;
        final ProcOr105pk0CpyfabgetMarkertypeLovResponsePoutListMarkertyp procOr105pk0cpyfabgetMarkertypeLovResponsePoutListMarkertyp = (ProcOr105pk0CpyfabgetMarkertypeLovResponsePoutListMarkertyp) o;
        return Objects.equals(getItemcod(), procOr105pk0cpyfabgetMarkertypeLovResponsePoutListMarkertyp.getItemcod()) &&
                Objects.equals(getMarkertypdes(), procOr105pk0cpyfabgetMarkertypeLovResponsePoutListMarkertyp.getMarkertypdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getItemcod(),
                getMarkertypdes());
    }
}