/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcOr105pk0CpyfabgetFaborienLovResponsePoutListFabOrient implements Serializable {


    @ColumnAlias("ITEMCOD")
    private String itemcod;

    @ColumnAlias("FABOREIENDES")
    private String faboreiendes;

    public String getItemcod() {
        return this.itemcod;
    }

    public void setItemcod(String itemcod) {
        this.itemcod = itemcod;
    }

    public String getFaboreiendes() {
        return this.faboreiendes;
    }

    public void setFaboreiendes(String faboreiendes) {
        this.faboreiendes = faboreiendes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcOr105pk0CpyfabgetFaborienLovResponsePoutListFabOrient)) return false;
        final ProcOr105pk0CpyfabgetFaborienLovResponsePoutListFabOrient procOr105pk0cpyfabgetFaborienLovResponsePoutListFabOrient = (ProcOr105pk0CpyfabgetFaborienLovResponsePoutListFabOrient) o;
        return Objects.equals(getItemcod(), procOr105pk0cpyfabgetFaborienLovResponsePoutListFabOrient.getItemcod()) &&
                Objects.equals(getFaboreiendes(), procOr105pk0cpyfabgetFaborienLovResponsePoutListFabOrient.getFaboreiendes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getItemcod(),
                getFaboreiendes());
    }
}