/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcOr105pk0CpyfabgetFabDetailsResponsePoutDetails implements Serializable {


    @ColumnAlias("INTFABCERTNO")
    private String intfabcertno;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    public String getIntfabcertno() {
        return this.intfabcertno;
    }

    public void setIntfabcertno(String intfabcertno) {
        this.intfabcertno = intfabcertno;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcOr105pk0CpyfabgetFabDetailsResponsePoutDetails)) return false;
        final ProcOr105pk0CpyfabgetFabDetailsResponsePoutDetails procOr105pk0cpyfabgetFabDetailsResponsePoutDetails = (ProcOr105pk0CpyfabgetFabDetailsResponsePoutDetails) o;
        return Objects.equals(getIntfabcertno(), procOr105pk0cpyfabgetFabDetailsResponsePoutDetails.getIntfabcertno()) &&
                Objects.equals(getOrdnum(), procOr105pk0cpyfabgetFabDetailsResponsePoutDetails.getOrdnum()) &&
                Objects.equals(getFabseq(), procOr105pk0cpyfabgetFabDetailsResponsePoutDetails.getFabseq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIntfabcertno(),
                getOrdnum(),
                getFabseq());
    }
}