/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcOr105pk0CpyfabgetShadeOptionLovResponse implements Serializable {


    @ColumnAlias("pOutListSahdeOption")
    private List<ProcOr105pk0CpyfabgetShadeOptionLovResponsePoutListSahdeOption> poutListSahdeOption;

    public List<ProcOr105pk0CpyfabgetShadeOptionLovResponsePoutListSahdeOption> getPoutListSahdeOption() {
        return this.poutListSahdeOption;
    }

    public void setPoutListSahdeOption(List<ProcOr105pk0CpyfabgetShadeOptionLovResponsePoutListSahdeOption> poutListSahdeOption) {
        this.poutListSahdeOption = poutListSahdeOption;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcOr105pk0CpyfabgetShadeOptionLovResponse)) return false;
        final ProcOr105pk0CpyfabgetShadeOptionLovResponse procOr105pk0cpyfabgetShadeOptionLovResponse = (ProcOr105pk0CpyfabgetShadeOptionLovResponse) o;
        return Objects.equals(getPoutListSahdeOption(), procOr105pk0cpyfabgetShadeOptionLovResponse.getPoutListSahdeOption());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutListSahdeOption());
    }
}