/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcOr105pk0CpyfabgetMarkertypeLovResponse implements Serializable {


    @ColumnAlias("pOutListMarkertyp")
    private List<ProcOr105pk0CpyfabgetMarkertypeLovResponsePoutListMarkertyp> poutListMarkertyp;

    public List<ProcOr105pk0CpyfabgetMarkertypeLovResponsePoutListMarkertyp> getPoutListMarkertyp() {
        return this.poutListMarkertyp;
    }

    public void setPoutListMarkertyp(List<ProcOr105pk0CpyfabgetMarkertypeLovResponsePoutListMarkertyp> poutListMarkertyp) {
        this.poutListMarkertyp = poutListMarkertyp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcOr105pk0CpyfabgetMarkertypeLovResponse)) return false;
        final ProcOr105pk0CpyfabgetMarkertypeLovResponse procOr105pk0cpyfabgetMarkertypeLovResponse = (ProcOr105pk0CpyfabgetMarkertypeLovResponse) o;
        return Objects.equals(getPoutListMarkertyp(), procOr105pk0cpyfabgetMarkertypeLovResponse.getPoutListMarkertyp());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutListMarkertyp());
    }
}