/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcOr105pk0CpyfabgetFabDetailsResponse implements Serializable {


    @ColumnAlias("pOutDetails")
    private List<ProcOr105pk0CpyfabgetFabDetailsResponsePoutDetails> poutDetails;

    public List<ProcOr105pk0CpyfabgetFabDetailsResponsePoutDetails> getPoutDetails() {
        return this.poutDetails;
    }

    public void setPoutDetails(List<ProcOr105pk0CpyfabgetFabDetailsResponsePoutDetails> poutDetails) {
        this.poutDetails = poutDetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcOr105pk0CpyfabgetFabDetailsResponse)) return false;
        final ProcOr105pk0CpyfabgetFabDetailsResponse procOr105pk0cpyfabgetFabDetailsResponse = (ProcOr105pk0CpyfabgetFabDetailsResponse) o;
        return Objects.equals(getPoutDetails(), procOr105pk0cpyfabgetFabDetailsResponse.getPoutDetails());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutDetails());
    }
}