/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VOr1000OrmnMaster generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`V_OR1000_ORMN_MASTER`")
public class VOr1000OrmnMaster implements Serializable {

    private String ordnum;
    private String wdsheetno;
    private String ctycod;
    private String clicod;
    private String clinam;
    private String cliacc;
    private String genre;
    private String cligrp;
    private LocalDateTime orddat;
    private String ordcat;
    private String ordertype;
    private String ordnumInitial;
    private String ordnumRoot;
    private String requestno;
    private String fastTrack;
    private String mrcid;
    private String wmerchname;
    private String ssn;
    private String ssncode;
    private String tyref;
    private String supnum;
    private String clionum;
    private LocalDateTime sshpdat;
    private Byte pckunt;
    private Integer qtyord;
    private String wqtyordUom;
    private String shpmod;
    private String clispcreq;
    private String orderstake;
    private String followupSts;
    private String dyelcn;
    private String maklcn;
    private String inimaklcn;
    private String invCligrp;
    private String freightTerm;
    private String pmttrm;
    private String ccycod;
    private String ccyret;
    private String ccyretb;
    private String ccyretc;
    private String ccyretd;
    private Double ccyrat;
    private String ordsts;
    private String prvsts;
    private LocalDateTime stsdat;
    private String prerelknt;
    private LocalDateTime prerelkdat;
    private String prekntid;
    private String prereldye;
    private LocalDateTime prerelddat;
    private String predyeid;
    private String relknt;
    private LocalDateTime relkdat;
    private String kntid;
    private String reldye;
    private LocalDateTime relddat;
    private String dyeid;
    private String relpof;
    private LocalDateTime relpdat;
    private String createid;
    private String kdstasklevel;
    private String refdes1;
    private String refdes2;
    private String refdes3;
    private String refdes4;
    private String refdes5;
    private String refdes6;
    private String refdes7;
    private String refdes8;
    private String refdes9;
    private String refdes10;
    private String gmtrefdesa;
    private String gmtrefdesb;
    private String gmtrefdesc;
    private String gmtrefdesd;

    @Id
    @Column(name = "`ORDNUM`", nullable = false, length = 12)
    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    @Column(name = "`W_DSHEETNO`", nullable = true, length = 4000)
    public String getWdsheetno() {
        return this.wdsheetno;
    }

    public void setWdsheetno(String wdsheetno) {
        this.wdsheetno = wdsheetno;
    }

    @Column(name = "`CTYCOD`", nullable = false, length = 3)
    public String getCtycod() {
        return this.ctycod;
    }

    public void setCtycod(String ctycod) {
        this.ctycod = ctycod;
    }

    @Column(name = "`CLICOD`", nullable = false, length = 10)
    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    @Column(name = "`CLINAM`", nullable = false, length = 40)
    public String getClinam() {
        return this.clinam;
    }

    public void setClinam(String clinam) {
        this.clinam = clinam;
    }

    @Column(name = "`CLIACC`", nullable = true, length = 8)
    public String getCliacc() {
        return this.cliacc;
    }

    public void setCliacc(String cliacc) {
        this.cliacc = cliacc;
    }

    @Column(name = "`GENRE`", nullable = true, length = 2)
    public String getGenre() {
        return this.genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    @Column(name = "`CLIGRP`", nullable = true, length = 8)
    public String getCligrp() {
        return this.cligrp;
    }

    public void setCligrp(String cligrp) {
        this.cligrp = cligrp;
    }

    @Column(name = "`ORDDAT`", nullable = false)
    public LocalDateTime getOrddat() {
        return this.orddat;
    }

    public void setOrddat(LocalDateTime orddat) {
        this.orddat = orddat;
    }

    @Column(name = "`ORDCAT`", nullable = true, length = 2)
    public String getOrdcat() {
        return this.ordcat;
    }

    public void setOrdcat(String ordcat) {
        this.ordcat = ordcat;
    }

    @Column(name = "`ORDERTYPE`", nullable = true, length = 1)
    public String getOrdertype() {
        return this.ordertype;
    }

    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype;
    }

    @Column(name = "`ORDNUM_INITIAL`", nullable = true, length = 12)
    public String getOrdnumInitial() {
        return this.ordnumInitial;
    }

    public void setOrdnumInitial(String ordnumInitial) {
        this.ordnumInitial = ordnumInitial;
    }

    @Column(name = "`ORDNUM_ROOT`", nullable = true, length = 12)
    public String getOrdnumRoot() {
        return this.ordnumRoot;
    }

    public void setOrdnumRoot(String ordnumRoot) {
        this.ordnumRoot = ordnumRoot;
    }

    @Column(name = "`REQUESTNO`", nullable = true, length = 170)
    public String getRequestno() {
        return this.requestno;
    }

    public void setRequestno(String requestno) {
        this.requestno = requestno;
    }

    @Column(name = "`FAST_TRACK`", nullable = true, length = 1)
    public String getFastTrack() {
        return this.fastTrack;
    }

    public void setFastTrack(String fastTrack) {
        this.fastTrack = fastTrack;
    }

    @Column(name = "`MRCID`", nullable = false, length = 6)
    public String getMrcid() {
        return this.mrcid;
    }

    public void setMrcid(String mrcid) {
        this.mrcid = mrcid;
    }

    @Column(name = "`W_MERCHNAME`", nullable = true, length = 30)
    public String getWmerchname() {
        return this.wmerchname;
    }

    public void setWmerchname(String wmerchname) {
        this.wmerchname = wmerchname;
    }

    @Column(name = "`SSN`", nullable = true, length = 5)
    public String getSsn() {
        return this.ssn;
    }

    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    @Column(name = "`SSNCODE`", nullable = true, length = 4)
    public String getSsncode() {
        return this.ssncode;
    }

    public void setSsncode(String ssncode) {
        this.ssncode = ssncode;
    }

    @Column(name = "`TYREF`", nullable = true, length = 30)
    public String getTyref() {
        return this.tyref;
    }

    public void setTyref(String tyref) {
        this.tyref = tyref;
    }

    @Column(name = "`SUPNUM`", nullable = true, length = 15)
    public String getSupnum() {
        return this.supnum;
    }

    public void setSupnum(String supnum) {
        this.supnum = supnum;
    }

    @Column(name = "`CLIONUM`", nullable = true, length = 40)
    public String getClionum() {
        return this.clionum;
    }

    public void setClionum(String clionum) {
        this.clionum = clionum;
    }

    @Column(name = "`SSHPDAT`", nullable = true)
    public LocalDateTime getSshpdat() {
        return this.sshpdat;
    }

    public void setSshpdat(LocalDateTime sshpdat) {
        this.sshpdat = sshpdat;
    }

    @Column(name = "`PCKUNT`", nullable = true, scale = 0, precision = 2)
    public Byte getPckunt() {
        return this.pckunt;
    }

    public void setPckunt(Byte pckunt) {
        this.pckunt = pckunt;
    }

    @Column(name = "`QTYORD`", nullable = true, scale = 0, precision = 6)
    public Integer getQtyord() {
        return this.qtyord;
    }

    public void setQtyord(Integer qtyord) {
        this.qtyord = qtyord;
    }

    @Column(name = "`W_QTYORD_UOM`", nullable = true, length = 6)
    public String getWqtyordUom() {
        return this.wqtyordUom;
    }

    public void setWqtyordUom(String wqtyordUom) {
        this.wqtyordUom = wqtyordUom;
    }

    @Column(name = "`SHPMOD`", nullable = true, length = 2)
    public String getShpmod() {
        return this.shpmod;
    }

    public void setShpmod(String shpmod) {
        this.shpmod = shpmod;
    }

    @Column(name = "`CLISPCREQ`", nullable = true, length = 7)
    public String getClispcreq() {
        return this.clispcreq;
    }

    public void setClispcreq(String clispcreq) {
        this.clispcreq = clispcreq;
    }

    @Column(name = "`ORDERSTAKE`", nullable = true, length = 5)
    public String getOrderstake() {
        return this.orderstake;
    }

    public void setOrderstake(String orderstake) {
        this.orderstake = orderstake;
    }

    @Column(name = "`FOLLOWUP_STS`", nullable = true, length = 5)
    public String getFollowupSts() {
        return this.followupSts;
    }

    public void setFollowupSts(String followupSts) {
        this.followupSts = followupSts;
    }

    @Column(name = "`DYELCN`", nullable = true, length = 6)
    public String getDyelcn() {
        return this.dyelcn;
    }

    public void setDyelcn(String dyelcn) {
        this.dyelcn = dyelcn;
    }

    @Column(name = "`MAKLCN`", nullable = true, length = 6)
    public String getMaklcn() {
        return this.maklcn;
    }

    public void setMaklcn(String maklcn) {
        this.maklcn = maklcn;
    }

    @Column(name = "`INIMAKLCN`", nullable = true, length = 6)
    public String getInimaklcn() {
        return this.inimaklcn;
    }

    public void setInimaklcn(String inimaklcn) {
        this.inimaklcn = inimaklcn;
    }

    @Column(name = "`INV_CLIGRP`", nullable = true, length = 8)
    public String getInvCligrp() {
        return this.invCligrp;
    }

    public void setInvCligrp(String invCligrp) {
        this.invCligrp = invCligrp;
    }

    @Column(name = "`FREIGHT_TERM`", nullable = true, length = 3)
    public String getFreightTerm() {
        return this.freightTerm;
    }

    public void setFreightTerm(String freightTerm) {
        this.freightTerm = freightTerm;
    }

    @Column(name = "`PMTTRM`", nullable = true, length = 2)
    public String getPmttrm() {
        return this.pmttrm;
    }

    public void setPmttrm(String pmttrm) {
        this.pmttrm = pmttrm;
    }

    @Column(name = "`CCYCOD`", nullable = true, length = 3)
    public String getCcycod() {
        return this.ccycod;
    }

    public void setCcycod(String ccycod) {
        this.ccycod = ccycod;
    }

    @Column(name = "`CCYRET`", nullable = true, length = 3)
    public String getCcyret() {
        return this.ccyret;
    }

    public void setCcyret(String ccyret) {
        this.ccyret = ccyret;
    }

    @Column(name = "`CCYRETB`", nullable = true, length = 3)
    public String getCcyretb() {
        return this.ccyretb;
    }

    public void setCcyretb(String ccyretb) {
        this.ccyretb = ccyretb;
    }

    @Column(name = "`CCYRETC`", nullable = true, length = 3)
    public String getCcyretc() {
        return this.ccyretc;
    }

    public void setCcyretc(String ccyretc) {
        this.ccyretc = ccyretc;
    }

    @Column(name = "`CCYRETD`", nullable = true, length = 3)
    public String getCcyretd() {
        return this.ccyretd;
    }

    public void setCcyretd(String ccyretd) {
        this.ccyretd = ccyretd;
    }

    @Column(name = "`CCYRAT`", nullable = true, scale = 2, precision = 8)
    public Double getCcyrat() {
        return this.ccyrat;
    }

    public void setCcyrat(Double ccyrat) {
        this.ccyrat = ccyrat;
    }

    @Column(name = "`ORDSTS`", nullable = false, length = 3)
    public String getOrdsts() {
        return this.ordsts;
    }

    public void setOrdsts(String ordsts) {
        this.ordsts = ordsts;
    }

    @Column(name = "`PRVSTS`", nullable = true, length = 3)
    public String getPrvsts() {
        return this.prvsts;
    }

    public void setPrvsts(String prvsts) {
        this.prvsts = prvsts;
    }

    @Column(name = "`STSDAT`", nullable = true)
    public LocalDateTime getStsdat() {
        return this.stsdat;
    }

    public void setStsdat(LocalDateTime stsdat) {
        this.stsdat = stsdat;
    }

    @Column(name = "`PRERELKNT`", nullable = true, length = 1)
    public String getPrerelknt() {
        return this.prerelknt;
    }

    public void setPrerelknt(String prerelknt) {
        this.prerelknt = prerelknt;
    }

    @Column(name = "`PRERELKDAT`", nullable = true)
    public LocalDateTime getPrerelkdat() {
        return this.prerelkdat;
    }

    public void setPrerelkdat(LocalDateTime prerelkdat) {
        this.prerelkdat = prerelkdat;
    }

    @Column(name = "`PREKNTID`", nullable = true, length = 6)
    public String getPrekntid() {
        return this.prekntid;
    }

    public void setPrekntid(String prekntid) {
        this.prekntid = prekntid;
    }

    @Column(name = "`PRERELDYE`", nullable = true, length = 1)
    public String getPrereldye() {
        return this.prereldye;
    }

    public void setPrereldye(String prereldye) {
        this.prereldye = prereldye;
    }

    @Column(name = "`PRERELDDAT`", nullable = true)
    public LocalDateTime getPrerelddat() {
        return this.prerelddat;
    }

    public void setPrerelddat(LocalDateTime prerelddat) {
        this.prerelddat = prerelddat;
    }

    @Column(name = "`PREDYEID`", nullable = true, length = 6)
    public String getPredyeid() {
        return this.predyeid;
    }

    public void setPredyeid(String predyeid) {
        this.predyeid = predyeid;
    }

    @Column(name = "`RELKNT`", nullable = true, length = 1)
    public String getRelknt() {
        return this.relknt;
    }

    public void setRelknt(String relknt) {
        this.relknt = relknt;
    }

    @Column(name = "`RELKDAT`", nullable = true)
    public LocalDateTime getRelkdat() {
        return this.relkdat;
    }

    public void setRelkdat(LocalDateTime relkdat) {
        this.relkdat = relkdat;
    }

    @Column(name = "`KNTID`", nullable = true, length = 6)
    public String getKntid() {
        return this.kntid;
    }

    public void setKntid(String kntid) {
        this.kntid = kntid;
    }

    @Column(name = "`RELDYE`", nullable = true, length = 1)
    public String getReldye() {
        return this.reldye;
    }

    public void setReldye(String reldye) {
        this.reldye = reldye;
    }

    @Column(name = "`RELDDAT`", nullable = true)
    public LocalDateTime getRelddat() {
        return this.relddat;
    }

    public void setRelddat(LocalDateTime relddat) {
        this.relddat = relddat;
    }

    @Column(name = "`DYEID`", nullable = true, length = 6)
    public String getDyeid() {
        return this.dyeid;
    }

    public void setDyeid(String dyeid) {
        this.dyeid = dyeid;
    }

    @Column(name = "`RELPOF`", nullable = true, length = 1)
    public String getRelpof() {
        return this.relpof;
    }

    public void setRelpof(String relpof) {
        this.relpof = relpof;
    }

    @Column(name = "`RELPDAT`", nullable = true)
    public LocalDateTime getRelpdat() {
        return this.relpdat;
    }

    public void setRelpdat(LocalDateTime relpdat) {
        this.relpdat = relpdat;
    }

    @Column(name = "`CREATEID`", nullable = true, length = 6)
    public String getCreateid() {
        return this.createid;
    }

    public void setCreateid(String createid) {
        this.createid = createid;
    }

    @Column(name = "`KDSTASKLEVEL`", nullable = true, length = 20)
    public String getKdstasklevel() {
        return this.kdstasklevel;
    }

    public void setKdstasklevel(String kdstasklevel) {
        this.kdstasklevel = kdstasklevel;
    }

    @Column(name = "`REFDES1`", nullable = true, length = 15)
    public String getRefdes1() {
        return this.refdes1;
    }

    public void setRefdes1(String refdes1) {
        this.refdes1 = refdes1;
    }

    @Column(name = "`REFDES2`", nullable = true, length = 15)
    public String getRefdes2() {
        return this.refdes2;
    }

    public void setRefdes2(String refdes2) {
        this.refdes2 = refdes2;
    }

    @Column(name = "`REFDES3`", nullable = true, length = 15)
    public String getRefdes3() {
        return this.refdes3;
    }

    public void setRefdes3(String refdes3) {
        this.refdes3 = refdes3;
    }

    @Column(name = "`REFDES4`", nullable = true, length = 15)
    public String getRefdes4() {
        return this.refdes4;
    }

    public void setRefdes4(String refdes4) {
        this.refdes4 = refdes4;
    }

    @Column(name = "`REFDES5`", nullable = true, length = 15)
    public String getRefdes5() {
        return this.refdes5;
    }

    public void setRefdes5(String refdes5) {
        this.refdes5 = refdes5;
    }

    @Column(name = "`REFDES6`", nullable = true, length = 15)
    public String getRefdes6() {
        return this.refdes6;
    }

    public void setRefdes6(String refdes6) {
        this.refdes6 = refdes6;
    }

    @Column(name = "`REFDES7`", nullable = true, length = 15)
    public String getRefdes7() {
        return this.refdes7;
    }

    public void setRefdes7(String refdes7) {
        this.refdes7 = refdes7;
    }

    @Column(name = "`REFDES8`", nullable = true, length = 15)
    public String getRefdes8() {
        return this.refdes8;
    }

    public void setRefdes8(String refdes8) {
        this.refdes8 = refdes8;
    }

    @Column(name = "`REFDES9`", nullable = true, length = 15)
    public String getRefdes9() {
        return this.refdes9;
    }

    public void setRefdes9(String refdes9) {
        this.refdes9 = refdes9;
    }

    @Column(name = "`REFDES10`", nullable = true, length = 15)
    public String getRefdes10() {
        return this.refdes10;
    }

    public void setRefdes10(String refdes10) {
        this.refdes10 = refdes10;
    }

    @Column(name = "`GMTREFDESA`", nullable = true, length = 15)
    public String getGmtrefdesa() {
        return this.gmtrefdesa;
    }

    public void setGmtrefdesa(String gmtrefdesa) {
        this.gmtrefdesa = gmtrefdesa;
    }

    @Column(name = "`GMTREFDESB`", nullable = true, length = 15)
    public String getGmtrefdesb() {
        return this.gmtrefdesb;
    }

    public void setGmtrefdesb(String gmtrefdesb) {
        this.gmtrefdesb = gmtrefdesb;
    }

    @Column(name = "`GMTREFDESC`", nullable = true, length = 15)
    public String getGmtrefdesc() {
        return this.gmtrefdesc;
    }

    public void setGmtrefdesc(String gmtrefdesc) {
        this.gmtrefdesc = gmtrefdesc;
    }

    @Column(name = "`GMTREFDESD`", nullable = true, length = 15)
    public String getGmtrefdesd() {
        return this.gmtrefdesd;
    }

    public void setGmtrefdesd(String gmtrefdesd) {
        this.gmtrefdesd = gmtrefdesd;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof VOr1000OrmnMaster)) return false;
        final VOr1000OrmnMaster vor1000ormnMaster = (VOr1000OrmnMaster) o;
        return Objects.equals(getOrdnum(), vor1000ormnMaster.getOrdnum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum());
    }
}