/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryCl565pk0funcIsExtnetClientResponse implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("ISEXTRANETCLIENT")
    private String isextranetclient;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getIsextranetclient() {
        return this.isextranetclient;
    }

    public void setIsextranetclient(String isextranetclient) {
        this.isextranetclient = isextranetclient;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryCl565pk0funcIsExtnetClientResponse)) return false;
        final QryCl565pk0funcIsExtnetClientResponse qryCl565pk0funcIsExtnetClientResponse = (QryCl565pk0funcIsExtnetClientResponse) o;
        return Objects.equals(getOrdnum(), qryCl565pk0funcIsExtnetClientResponse.getOrdnum()) &&
                Objects.equals(getIsextranetclient(), qryCl565pk0funcIsExtnetClientResponse.getIsextranetclient());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getIsextranetclient());
    }
}