/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryGetChgReasonListResponse implements Serializable {


    @ColumnAlias("REASONCODE")
    private String reasoncode;

    @ColumnAlias("REASONCATEGORY")
    private String reasoncategory;

    @ColumnAlias("REASONSUBCATEGORY")
    private String reasonsubcategory;

    public String getReasoncode() {
        return this.reasoncode;
    }

    public void setReasoncode(String reasoncode) {
        this.reasoncode = reasoncode;
    }

    public String getReasoncategory() {
        return this.reasoncategory;
    }

    public void setReasoncategory(String reasoncategory) {
        this.reasoncategory = reasoncategory;
    }

    public String getReasonsubcategory() {
        return this.reasonsubcategory;
    }

    public void setReasonsubcategory(String reasonsubcategory) {
        this.reasonsubcategory = reasonsubcategory;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryGetChgReasonListResponse)) return false;
        final QryGetChgReasonListResponse qryGetChgReasonListResponse = (QryGetChgReasonListResponse) o;
        return Objects.equals(getReasoncode(), qryGetChgReasonListResponse.getReasoncode()) &&
                Objects.equals(getReasoncategory(), qryGetChgReasonListResponse.getReasoncategory()) &&
                Objects.equals(getReasonsubcategory(), qryGetChgReasonListResponse.getReasonsubcategory());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getReasoncode(),
                getReasoncategory(),
                getReasonsubcategory());
    }
}