/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryOrt205shpnumLovResponse implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("SHPNUM")
    private String shpnum;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getShpnum() {
        return this.shpnum;
    }

    public void setShpnum(String shpnum) {
        this.shpnum = shpnum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryOrt205shpnumLovResponse)) return false;
        final QryOrt205shpnumLovResponse qryOrt205shpnumLovResponse = (QryOrt205shpnumLovResponse) o;
        return Objects.equals(getOrdnum(), qryOrt205shpnumLovResponse.getOrdnum()) &&
                Objects.equals(getShpnum(), qryOrt205shpnumLovResponse.getShpnum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getShpnum());
    }
}