/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryOrt209refColnameResponse implements Serializable {


    @ColumnAlias("REF")
    private String ref;

    @ColumnAlias("REF2")
    private String ref2;

    @ColumnAlias("REF3")
    private String ref3;

    @ColumnAlias("REF4")
    private String ref4;

    @ColumnAlias("REF5")
    private String ref5;

    @ColumnAlias("REF6")
    private String ref6;

    @ColumnAlias("REF7")
    private String ref7;

    @ColumnAlias("REF8")
    private String ref8;

    public String getRef() {
        return this.ref;
    }

    public void setRef(String ref) {
        this.ref = ref;
    }

    public String getRef2() {
        return this.ref2;
    }

    public void setRef2(String ref2) {
        this.ref2 = ref2;
    }

    public String getRef3() {
        return this.ref3;
    }

    public void setRef3(String ref3) {
        this.ref3 = ref3;
    }

    public String getRef4() {
        return this.ref4;
    }

    public void setRef4(String ref4) {
        this.ref4 = ref4;
    }

    public String getRef5() {
        return this.ref5;
    }

    public void setRef5(String ref5) {
        this.ref5 = ref5;
    }

    public String getRef6() {
        return this.ref6;
    }

    public void setRef6(String ref6) {
        this.ref6 = ref6;
    }

    public String getRef7() {
        return this.ref7;
    }

    public void setRef7(String ref7) {
        this.ref7 = ref7;
    }

    public String getRef8() {
        return this.ref8;
    }

    public void setRef8(String ref8) {
        this.ref8 = ref8;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryOrt209refColnameResponse)) return false;
        final QryOrt209refColnameResponse qryOrt209refColnameResponse = (QryOrt209refColnameResponse) o;
        return Objects.equals(getRef(), qryOrt209refColnameResponse.getRef()) &&
                Objects.equals(getRef2(), qryOrt209refColnameResponse.getRef2()) &&
                Objects.equals(getRef3(), qryOrt209refColnameResponse.getRef3()) &&
                Objects.equals(getRef4(), qryOrt209refColnameResponse.getRef4()) &&
                Objects.equals(getRef5(), qryOrt209refColnameResponse.getRef5()) &&
                Objects.equals(getRef6(), qryOrt209refColnameResponse.getRef6()) &&
                Objects.equals(getRef7(), qryOrt209refColnameResponse.getRef7()) &&
                Objects.equals(getRef8(), qryOrt209refColnameResponse.getRef8());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRef(),
                getRef2(),
                getRef3(),
                getRef4(),
                getRef5(),
                getRef6(),
                getRef7(),
                getRef8());
    }
}