/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.mu.cmt.pfs.pfsdb.models.query.*;

public interface PfsdbQueryExecutorService {

    Page<QryOrt209currentPriceResponse> executeQryOrt209CurrentPrice(String pordnum, String pshpnum, String pseqcod, Integer pszeseq, Pageable pageable);

    void exportQryOrt209CurrentPrice(String pordnum, String pshpnum, String pseqcod, Integer pszeseq, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    QryOr207pk0untprcAccessResponse executeQryOr207pk0UntprcAccess(String pordnum, String pprgid, String puserAppRoleList);

    Page<QryOrt205shpnumLovResponse> executeQryOrt205ShpnumLov(String pordnum, Pageable pageable);

    void exportQryOrt205ShpnumLov(String pordnum, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryCl565pk0funcIsExtnetClientResponse> executeQryCl565pk0FuncIsExtnetClient(String pordnum, Pageable pageable);

    void exportQryCl565pk0FuncIsExtnetClient(String pordnum, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryGetChgReasonListResponse> executeQryGetChgReasonList(String pchangeCategory, Pageable pageable);

    void exportQryGetChgReasonList(String pchangeCategory, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryOrt209refColnameResponse> executeQryOrt209RefColname(String pordnum, Pageable pageable);

    void exportQryOrt209RefColname(String pordnum, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<QryShpnumLovResponse> executeQryShpnumLov(String pordnum, Pageable pageable);

    void exportQryShpnumLov(String pordnum, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    QryOr105wpk0yrnGetDefBaseyrnclrResponse executeQryOr105wpk0YrnGetDefBaseyrnclr(String pprgid, String pyrnclr, String pbaseyrnclr);

    Page<QryRft102clirefColnameResponse> executeQryRft102ClirefColname(String pclicod, Pageable pageable);

    void exportQryRft102ClirefColname(String pclicod, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    QrySy9200pk0getUrlUpchargesResponse executeQrySy9200pk0GetUrlUpcharges(String potherParams);

    Page<QryOrt207currentPriceResponse> executeQryOrt207CurrentPrice(String pordnum, String ppricecat, String pseqcod, String pclionum, String pszeseq, Pageable pageable);

    void exportQryOrt207CurrentPrice(String pordnum, String ppricecat, String pseqcod, String pclionum, String pszeseq, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    QryCcffabDetailsResponse executeQryCCFFabDetails(String pordnum, Integer pfabseq);

}