/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.InputStream;

import com.mu.cmt.pfs.pfsdb.models.procedure.*;

public interface PfsdbProcedureExecutorService {

    Void executeOr207pk0ReleaseKDSPrice(String pordnum, String pusrid, String pprgid, String puserAppRoleList);

    Or207pk0searchOrdRefResponse executeOr207pk0SearchOrdRef(String pclicod, String pssn, String pclionum, String pref, String pref2, String pref3, String pref4, String pref5, String pref6, String pref7, String pref8, String pusrid, String pprgname);

    Or105wpk0yrnGetYrnclrResponse executeOr105wpk0yrn_getYrnclr(String pprgid, String pbaseyrnUseind);

    Void executeOr207pk0FetchPackSze(String pordnum, String ppricecat);

    Or207pk0getOrt205recordResponse executeOr207pk0GetOrt205Record(String pordnum);

    Or105wpk0yrnGetyrncpsResponse executeOr105wpk0yrn_getyrncps(String pprgid);

    Void executeOr207pk0ReleaseRef(String pordnum, String pusrid, String pprgid);

    Or105wpk0yrnGetyrncntResponse executeOr105wpk0yrn_getyrncnt(String pprgid);

    Void executeOr207pk0CopyRef(String psrcOrdnum, String pdestOrdnum, String psrcShpnum, String pdestShpnum, String pcopyFliprcInd, String pcopyRetPrcInd, String pcopyrefInd, String pcopyref2ind, String pcopyref3ind, String pcopyref4ind, String pcopyref5ind, String pcopyref6ind, String pcopyref7ind, String pcopyref8ind, String pusrid, String pprgname);

    Or207pk0getOrt209recordResponse executeOr207pk0GetOrt209Record(String pordnum, String pshpnum);

    Or105wpk0yrnGetYrnffcodResponse executeOr105wpk0yrn_getYrnffcod(String pprgid, String pordnum, Integer pfabseq, Integer pyrnseq);

    Or105wpk0yrnGetYrnsubqltyBResponse executeOr105wpk0Yrn_getYrnsubqltyB(String pprgid, String pyrnqlty);

    Or105wpk0yrnGetYrnsubqltyResponse executeOr105wpk0yrn_getYrnsubqlty(String pprgid, String pyrnqlty, String psubqltytyp);

    InputStream executeProcOR105PK0_CPYFABGetFabBlob(String pprgId, String plibRefNo, String pfaceSide);

    Or207pk0fetchExtranetDetailsResponse executeOr207pk0FetchExtranetDetails(String pordnum, String pfromShpnum, String ptoShpnum, String pfetchUnitprcInd, String pfetchRetPrcInd, String pfetchBarcodeInd, String pfetchRatioPackInd, String pfetchStyleInd, String pusrid, String pprgname, String puserAppRoleList);

    CreateProcOr105pk0CpyfabinsCpyFabResponse executeCreateProcOR105PK0_CPYFABInsCpyFab(CreateProcOr105pk0CpyfabinsCpyFabRequest createProcOr105pk0cpyfabinsCpyFabRequest);

    ProcOr105pk0CpyfabgetMarkertypeLovResponse executeProcOR105PK0_CPYFABGetMarkertypeLOV(String pprgId);

    Or105wpk0YrnValRecordOrt125Response executeOr105wpk0_yrnValRecordORT125(String pprgid, String pyrnrow);

    Or207pk0getKdspriceChgHistoryResponse executeOr207pk0GetKDSPriceChgHistory(String pordnum, String pshpnum);

    Or207pk0getRefreldatesResponse executeOr207pk0GetRefreldates(String pordnum);

    Or105pk0repSameYarnUpdCcfResponse executeOr105pk0RepSameYarn_UpdCCF(String pprgid, String pordnum, String pfabseq, String pyrnpropvalList);

    Void executeOr207pk0UpdPriceOrt207(String pordnum, String ppricecat, String pseqcod, Integer pszeseq, String pclionum, Double punitprcAir, Double punitprcSea, Double pfliprcAir, Double pfliprcSea, String pretprc, String pretprcb, String pretprcc, String pretprcd, String pusrid, String pprogid, String pchangereason, String puserRemarks, String pupdAllSzeInd, String pupdAllPackInd, String pupdAllClionumInd);

    ProcOr105pk0CpyfabgetCpyFabResponse executeProcOR105PK0_CPYFABGetCpyFab(String pprgId, String pordnum, Integer pfabSeq, String pdestOrdnum);

    ProcOr105pk0CpyfabgetFabSeqLovResponse executeProcOR105PK0_CPYFABGetFabSeqLOV(String pprgId, String pordnum);

    Or105wpk0yrnGetYrnqltyResponse executeOr105wpk0yrn_getYrnqlty(String pprgid);

    ProcOr105pk0CpyfabgetFaborienLovResponse executeProcOR105PK0_CPYFABGetFaborienLOV(String pprgId);

    Or105wpk0YrnGetOriclrResponse executeOr105wpk0_yrn_getOriclr(String pprgid, String pyrnclr, String pyrncnt, String pyrncps);

    Or105wpk0qryOrt125Response executeOr105wpk0QryOrt125(String pprgid, String pordnum, Integer pfabseq);

    ProcOr105pk0CpyfabgetFabDetailsResponse executeProcOR105PK0_CPYFABGetFabDetails(String pprgId, String pordnum, Integer pfabSeq, String pccf, String poption);

    Or207pk0getChgReasonResponse executeOr207pk0GetChgReason(String pchangeCategory);

    Or207pk0getCmtPriceChgHistoryResponse executeOr207pk0GetCmtPriceChgHistory(String pordnum);

    ProcOr105pk0CpyfabgetShadeOptionLovResponse executeProcOR105PK0_CPYFABGetShadeOptionLOV(String pprgId, String pintreftno);

    Void executeOr207pk0PrePostUpdOrt209(String pordnum, String pseqcod, Integer pszeseq, String pshpnum, String pfieldToUpdate, Double pkdsunitprc, Double pfliprc, Double pkdsRetprc, Double pkdsRetprcb, Double pkdsRetprcc, Double pkdsRetprcd, String pusrid, String pprgid, String pchangereason, String puserRemarks, String pref, String pref2, String pref3, String pref4, String pref5, String pref6, String pref7, String pref8, String pupdAllSzeInd, String pupdAllPackInd, String pupdAllShpNumInd, String puserAppRoleList);

}